/*
 * JS for menu_shared generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '148444cb-eb26-4cec-bc22-29bf794bc529';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "aboutPage",
    "location": "aboutPage.html"
}, {
    "name": "itemDetailsPage",
    "location": "itemDetailsPage.html"
}, {
    "name": "menuHeadingManagePage",
    "location": "menuHeadingManagePage.html"
}, {
    "name": "proprietorAnalyticsPage",
    "location": "proprietorAnalyticsPage.html"
}, {
    "name": "zzpromoEdit",
    "location": "zzpromoEdit.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "itemPage",
    "location": "itemPage.html"
}, {
    "name": "zzpromoManage",
    "location": "zzpromoManage.html"
}, {
    "name": "zzscannerPage",
    "location": "zzscannerPage.html"
}, {
    "name": "zztimeRangePage",
    "location": "zztimeRangePage.html"
}, {
    "name": "selectedPage",
    "location": "selectedPage.html"
}, {
    "name": "zzCSStestPage",
    "location": "zzCSStestPage.html"
}, {
    "name": "zzmenuPage",
    "location": "zzmenuPage.html"
}, {
    "name": "menuHistoryPage",
    "location": "menuHistoryPage.html"
}, {
    "name": "faqPage",
    "location": "faqPage.html"
}, {
    "name": "zzratingInfoPage",
    "location": "zzratingInfoPage.html"
}, {
    "name": "orderHistoryPage",
    "location": "orderHistoryPage.html"
}, {
    "name": "createAccount",
    "location": "createAccount.html"
}, {
    "name": "itemManagePage",
    "location": "itemManagePage.html"
}, {
    "name": "proprietorStartPage",
    "location": "proprietorStartPage.html"
}, {
    "name": "operationsRestaurantPage",
    "location": "operationsRestaurantPage.html"
}, {
    "name": "zzdetailedReviewPage",
    "location": "zzdetailedReviewPage.html"
}, {
    "name": "itemEditPage",
    "location": "itemEditPage.html"
}, {
    "name": "selectionHistoryPage",
    "location": "selectionHistoryPage.html"
}, {
    "name": "zzproprietorStatPage",
    "location": "zzproprietorStatPage.html"
}, {
    "name": "zzitemInventoryPage",
    "location": "zzitemInventoryPage.html"
}, {
    "name": "zzalertPage",
    "location": "zzalertPage.html"
}, {
    "name": "zzsearchPage",
    "location": "zzsearchPage.html"
}, {
    "name": "menuPage_v2",
    "location": "menuPage_v2.html"
}, {
    "name": "zzqrCodePage",
    "location": "zzqrCodePage.html"
}, {
    "name": "profilePage",
    "location": "profilePage.html"
}, {
    "name": "filterPage",
    "location": "filterPage.html"
}, {
    "name": "easterEggPage",
    "location": "easterEggPage.html"
}, {
    "name": "helpPage",
    "location": "helpPage.html"
}, {
    "name": "navigatePage",
    "location": "navigatePage.html"
}, {
    "name": "menuPreviewPage",
    "location": "menuPreviewPage.html"
}, {
    "name": "zzfacebookLogin",
    "location": "zzfacebookLogin.html"
}, {
    "name": "menu_shared",
    "location": "menu_shared.html"
}, {
    "name": "logoutPage",
    "location": "logoutPage.html"
}, {
    "name": "favoritesPage",
    "location": "favoritesPage.html"
}, {
    "name": "proprietorPage",
    "location": "proprietorPage.html"
}, {
    "name": "wishListPage",
    "location": "wishListPage.html"
}, {
    "name": "menuManagementPage",
    "location": "menuManagementPage.html"
}, {
    "name": "touPage",
    "location": "touPage.html"
}, {
    "name": "zzsettingsPage",
    "location": "zzsettingsPage.html"
}];

function menu_shared_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["menu_shared_manushared_vendor_details_get_onsuccess_mapping_0"] = {
        "homeScreen": "menu_shared",
        "directions": [
            {
                "from_name": "manushared_vendor_details_get",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "currentVendor",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['businessName']",
                        "target": "$['businessName']"
                    },
                    {
                        "source": "$['body']['_id']",
                        "target": "$['id']"
                    },
                    {
                        "source": "$['body']['vendorDescription']",
                        "target": "$['vendorDescription']"
                    },
                    {
                        "source": "$['body']['businessType']",
                        "target": "$['businessType']"
                    },
                    {
                        "source": "$['body']['menuTagLine']",
                        "target": "$['menuTagLine']"
                    },
                    {
                        "source": "$['body']['taxRate']",
                        "target": "$['taxRate']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["menu_shared_manushared_vendor_details_get_onbeforesend_mapping_0"] = {
        "homeScreen": "menu_shared",
        "directions": [
            {
                "from_name": "vendorId",
                "from_type": "SESSION_STORAGE",
                "to_name": "manushared_vendor_details_get",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}"
                    },
                    "parameters": {
                        "include": "state,country"
                    },
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['_id']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["menu_shared_menushared_login_service_onsuccess_mapping_0"] = {
        "homeScreen": "menu_shared",
        "directions": [
            {
                "from_name": "menushared_login_service",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "userId",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['_id']",
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "menushared_login_service",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "sessionToken",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['sessionToken']",
                        "target": "$"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["menu_shared_menushared_login_service_onbeforesend_mapping_0"] = {
        "homeScreen": "menu_shared",
        "directions": [
            {
                "to_name": "menushared_login_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": []
            }
        ]
    };
    Apperyio.mappings["menu_shared_menuShared_vendor_read_service_onsuccess_mapping_0"] = {
        "homeScreen": "menu_shared",
        "directions": []
    };
    Apperyio.mappings["menu_shared_menuShared_vendor_read_service_onbeforesend_mapping_0"] = {
        "homeScreen": "menu_shared",
        "directions": [
            {
                "from_name": "vendorId",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuShared_vendor_read_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}"
                    },
                    "parameters": {
                        "include": "state,country"
                    },
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['_id']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["menu_shared_menuShared_usetTypeService_onsuccess_mapping_0"] = {
        "homeScreen": "menu_shared",
        "directions": [
            {
                "from_name": "menuShared_usetTypeService",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "userType",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['userType']",
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "menuShared_usetTypeService",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "qrcodeFileName",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['qrcodeFileName']",
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "menuShared_usetTypeService",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "userId",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['_id']",
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "menuShared_usetTypeService",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "userPrefs",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['includePrefs']",
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "menuShared_usetTypeService",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "zipCode",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['zip']",
                        "target": "$"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["menu_shared_menuShared_usetTypeService_onbeforesend_mapping_0"] = {
        "homeScreen": "menu_shared",
        "directions": [
            {
                "from_name": "userId",
                "from_type": "LOCAL_STORAGE",
                "to_name": "menuShared_usetTypeService",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['userId']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.manushared_vendor_details_get = Apperyio.datasources.manushared_vendor_details_get = new Apperyio.DataSource(projectMdb1_vendor_read_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["menu_shared_manushared_vendor_details_get_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["menu_shared_manushared_vendor_details_get_onsuccess_mapping_0"]);
            var vendor_id = urlParam('vendor');
            if (vendor_id) {
                // var currentVendor = {} ;
                // currentVendor.id = vendor_id ;
                // storageSet('currentVendor', currentVendor);
                // storageSet('vendorId', vendor_id);
                projectMdb1_settings.vendor_id = vendor_id;
                if (xorKey.available()) {
                    var uname = xorKey.getLogin();
                    var pass = xorKey.getPassword();
                    menushared_login_service.execute({
                        data: {
                            username: uname,
                            password: pass
                        }
                    });
                    storageSet('userName', uname);
                } else {
                    Apperyio('loginField').val('guest');
                    storageSet('userName', 'guest');
                    isGuest = true;
                    menushared_login_service.execute({
                        data: {
                            username: 'guest',
                            password: 'guest'
                        }
                    });
                }
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.menushared_login_service = Apperyio.datasources.menushared_login_service = new Apperyio.DataSource(projectMdb1_login_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["menu_shared_menushared_login_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["menu_shared_menushared_login_service_onsuccess_mapping_0"]);
            try {
                menuShared_usetTypeService.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
            userName = storageGet('userName');
            Settings.session_token = storageGet('sessionToken');
            customerMode = true;
            // if ((!isPhone || !customerMode) && !isGuest) 
            // {
            // 	projectMdb1_settings.vendor_id = storageGet('vendorId');
            // }    
            // if(customerMode)
            // {
            //     if(!isPhone)
            //     {
            //         var id = urlParam('vendor');
            //         if(id)
            //         {
            //             storageSet('vendorId', id);
            //             projectMdb1_settings.user_id = id;
            //             projectMdb1_settings.vendor_id = id;
            //         }
            //     }
            // }
            if (projectMdb1_settings.vendor_id) {
                // storageSet('vendorId', projectMdb1_settings.vendor_id);
                menuShared_vendor_read_service.execute({});
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.menuShared_vendor_read_service = Apperyio.datasources.menuShared_vendor_read_service = new Apperyio.DataSource(projectMdb1_vendor_read_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["menu_shared_menuShared_vendor_read_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["menu_shared_menuShared_vendor_read_service_onsuccess_mapping_0"]);
            console.log('time ~>', new Date().getTime());
            hideBackButton = true;
            Appery.navigateTo('menuPage_v2', {
                reverse: false,
                // hideBackButton: true
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.menuShared_usetTypeService = Apperyio.datasources.menuShared_usetTypeService = new Apperyio.DataSource(projectMdb1_user_details_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["menu_shared_menuShared_usetTypeService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["menu_shared_menuShared_usetTypeService_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'menu_shared';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var menu_shared_onLoad = function() {
        menu_shared_elementsExtraJS();
        storageSet('currentVendor', '');
        storageSet('menuHierarchyList', null);
        if (navigator.userAgent.match(/(iPhone|iPod|iPad|Android|BlackBerry|IEMobile)/)) {
            isPhone = true;
        }
        if (navigator.userAgent.match(/(iPhone|iPad)/)) {
            isApple = true;
        }
        projectMdb1_settings.vendor_id = null;
        var vendor_id = urlParam('vendor');
        if (vendor_id) {
            var currentVendor = {};
            currentVendor.id = vendor_id;
            storageSet('currentVendor', currentVendor);
            storageSet('vendorId', vendor_id);
            projectMdb1_settings.vendor_id = vendor_id;
            manushared_vendor_details_get.execute();
        };
        menu_shared_deviceEvents();
        menu_shared_windowEvents();
        menu_shared_elementsEvents();
    };
    // screen window events
    function menu_shared_windowEvents() {
        $('#menu_shared').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#menu_shared').on({
            focus: function(event) {
                console.log("asd");
            },
        });
    };
    // device events
    function menu_shared_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function menu_shared_elementsExtraJS() {
        // screen (menu_shared) extra code
    };
    // screen elements handler
    function menu_shared_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
    };
    $(document).off("pagebeforeshow", "#menu_shared").on("pagebeforeshow", "#menu_shared", function(event, ui) {
        Apperyio.CurrentScreen = "menu_shared";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    menu_shared_onLoad();
};
$(document).off("pagecreate", "#menu_shared").on("pagecreate", "#menu_shared", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    menu_shared_js();
});