/*
 * JS for menuHeadingManagePage generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '148444cb-eb26-4cec-bc22-29bf794bc529';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "aboutPage",
    "location": "aboutPage.html"
}, {
    "name": "itemDetailsPage",
    "location": "itemDetailsPage.html"
}, {
    "name": "menuHeadingManagePage",
    "location": "menuHeadingManagePage.html"
}, {
    "name": "proprietorAnalyticsPage",
    "location": "proprietorAnalyticsPage.html"
}, {
    "name": "zzpromoEdit",
    "location": "zzpromoEdit.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "itemPage",
    "location": "itemPage.html"
}, {
    "name": "zzpromoManage",
    "location": "zzpromoManage.html"
}, {
    "name": "zzscannerPage",
    "location": "zzscannerPage.html"
}, {
    "name": "zztimeRangePage",
    "location": "zztimeRangePage.html"
}, {
    "name": "selectedPage",
    "location": "selectedPage.html"
}, {
    "name": "zzCSStestPage",
    "location": "zzCSStestPage.html"
}, {
    "name": "zzmenuPage",
    "location": "zzmenuPage.html"
}, {
    "name": "menuHistoryPage",
    "location": "menuHistoryPage.html"
}, {
    "name": "faqPage",
    "location": "faqPage.html"
}, {
    "name": "zzratingInfoPage",
    "location": "zzratingInfoPage.html"
}, {
    "name": "orderHistoryPage",
    "location": "orderHistoryPage.html"
}, {
    "name": "createAccount",
    "location": "createAccount.html"
}, {
    "name": "itemManagePage",
    "location": "itemManagePage.html"
}, {
    "name": "proprietorStartPage",
    "location": "proprietorStartPage.html"
}, {
    "name": "operationsRestaurantPage",
    "location": "operationsRestaurantPage.html"
}, {
    "name": "zzdetailedReviewPage",
    "location": "zzdetailedReviewPage.html"
}, {
    "name": "itemEditPage",
    "location": "itemEditPage.html"
}, {
    "name": "selectionHistoryPage",
    "location": "selectionHistoryPage.html"
}, {
    "name": "zzproprietorStatPage",
    "location": "zzproprietorStatPage.html"
}, {
    "name": "zzitemInventoryPage",
    "location": "zzitemInventoryPage.html"
}, {
    "name": "zzalertPage",
    "location": "zzalertPage.html"
}, {
    "name": "zzsearchPage",
    "location": "zzsearchPage.html"
}, {
    "name": "menuPage_v2",
    "location": "menuPage_v2.html"
}, {
    "name": "zzqrCodePage",
    "location": "zzqrCodePage.html"
}, {
    "name": "profilePage",
    "location": "profilePage.html"
}, {
    "name": "filterPage",
    "location": "filterPage.html"
}, {
    "name": "easterEggPage",
    "location": "easterEggPage.html"
}, {
    "name": "helpPage",
    "location": "helpPage.html"
}, {
    "name": "navigatePage",
    "location": "navigatePage.html"
}, {
    "name": "menuPreviewPage",
    "location": "menuPreviewPage.html"
}, {
    "name": "zzfacebookLogin",
    "location": "zzfacebookLogin.html"
}, {
    "name": "menu_shared",
    "location": "menu_shared.html"
}, {
    "name": "logoutPage",
    "location": "logoutPage.html"
}, {
    "name": "favoritesPage",
    "location": "favoritesPage.html"
}, {
    "name": "proprietorPage",
    "location": "proprietorPage.html"
}, {
    "name": "wishListPage",
    "location": "wishListPage.html"
}, {
    "name": "menuManagementPage",
    "location": "menuManagementPage.html"
}, {
    "name": "touPage",
    "location": "touPage.html"
}, {
    "name": "zzsettingsPage",
    "location": "zzsettingsPage.html"
}];

function menuHeadingManagePage_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'homeButton': 'menuHeadingManagePage_homeButton',
        'headingManageLabel': 'menuHeadingManagePage_headingManageLabel',
        'buttonCellAddPreview': 'menuHeadingManagePage_buttonCellAddPreview',
        'addCell': 'menuHeadingManagePage_addCell',
        'itemAddButton': 'menuHeadingManagePage_itemAddButton',
        'previewCell': 'menuHeadingManagePage_previewCell',
        'expandCollapseAllButton': 'menuHeadingManagePage_expandCollapseAllButton',
        'menuPreviewButton': 'menuHeadingManagePage_menuPreviewButton',
        'menuList': 'menuHeadingManagePage_menuList',
        'headingItem': 'menuHeadingManagePage_headingItem',
        'menuHeadingName': 'menuHeadingManagePage_menuHeadingName',
        'mobilelistitembutton_38': 'menuHeadingManagePage_mobilelistitembutton_38',
        'menuHeadingDescription': 'menuHeadingManagePage_menuHeadingDescription',
        'priceGrid': 'menuHeadingManagePage_priceGrid',
        'dollarLabelCell': 'menuHeadingManagePage_dollarLabelCell',
        'dollarSignLabel': 'menuHeadingManagePage_dollarSignLabel',
        'priceCell': 'menuHeadingManagePage_priceCell',
        'price': 'menuHeadingManagePage_price',
        'hiddenCell': 'menuHeadingManagePage_hiddenCell',
        'hiddenStatus': 'menuHeadingManagePage_hiddenStatus',
        'headingAddLabel': 'menuHeadingManagePage_headingAddLabel',
        'headingAddError': 'menuHeadingManagePage_headingAddError',
        'headingAddField': 'menuHeadingManagePage_headingAddField',
        'headingDescriptionField': 'menuHeadingManagePage_headingDescriptionField',
        'categoryParentLabel': 'menuHeadingManagePage_categoryParentLabel',
        'headingExampleLabel1': 'menuHeadingManagePage_headingExampleLabel1',
        'headingExampleLabel2': 'menuHeadingManagePage_headingExampleLabel2',
        'headingExampleLabel3': 'menuHeadingManagePage_headingExampleLabel3',
        'headingParentSelect': 'menuHeadingManagePage_headingParentSelect',
        'headingParentSelect-0': 'menuHeadingManagePage_headingParentSelect-0',
        'buttonGrid': 'menuHeadingManagePage_buttonGrid',
        'saveCell': 'menuHeadingManagePage_saveCell',
        'headingAddSaveButton': 'menuHeadingManagePage_headingAddSaveButton',
        'deleteCell': 'menuHeadingManagePage_deleteCell',
        'deleteButton': 'menuHeadingManagePage_deleteButton',
        'headingEditLabel': 'menuHeadingManagePage_headingEditLabel',
        'headingField': 'menuHeadingManagePage_headingField',
        'categoryParentEditLabel': 'menuHeadingManagePage_categoryParentEditLabel',
        'categoryParentEditButton': 'menuHeadingManagePage_categoryParentEditButton',
        'categoryParentEditButton-0': 'menuHeadingManagePage_categoryParentEditButton-0',
        'headingButtonGrid': 'menuHeadingManagePage_headingButtonGrid',
        'headingSaveCell': 'menuHeadingManagePage_headingSaveCell',
        'categoryEditSaveButton': 'menuHeadingManagePage_categoryEditSaveButton',
        'headingCancelCell': 'menuHeadingManagePage_headingCancelCell',
        'headingCancelButton': 'menuHeadingManagePage_headingCancelButton',
        'headingDeleteConfirmLabel': 'menuHeadingManagePage_headingDeleteConfirmLabel',
        'deleteConfirmGrid': 'menuHeadingManagePage_deleteConfirmGrid',
        'deleteConfirmCell': 'menuHeadingManagePage_deleteConfirmCell',
        'deleteConfirmButton': 'menuHeadingManagePage_deleteConfirmButton',
        'deleteCancelCell': 'menuHeadingManagePage_deleteCancelCell',
        'deleteCancelButton': 'menuHeadingManagePage_deleteCancelButton',
        'moveFrom_label': 'menuHeadingManagePage_moveFrom_label',
        'moveHeadingFrom_grid': 'menuHeadingManagePage_moveHeadingFrom_grid',
        'mobilegridcell_42': 'menuHeadingManagePage_mobilegridcell_42',
        'moveFrom_button': 'menuHeadingManagePage_moveFrom_button',
        'mobilegridcell_43': 'menuHeadingManagePage_mobilegridcell_43',
        'moveFrom_cancel': 'menuHeadingManagePage_moveFrom_cancel',
        'moveToOrder_label': 'menuHeadingManagePage_moveToOrder_label',
        'moveToOrder_grid': 'menuHeadingManagePage_moveToOrder_grid',
        'mobilegridcell_52': 'menuHeadingManagePage_mobilegridcell_52',
        'moveToBefore_button': 'menuHeadingManagePage_moveToBefore_button',
        'mobilegridcell_53': 'menuHeadingManagePage_mobilegridcell_53',
        'moveToAfter_button': 'menuHeadingManagePage_moveToAfter_button',
        'mobilegridcell_56': 'menuHeadingManagePage_mobilegridcell_56',
        'moveTo_cancel': 'menuHeadingManagePage_moveTo_cancel',
        'mobilelabel_60': 'menuHeadingManagePage_mobilelabel_60',
        'moveToChild_grid': 'menuHeadingManagePage_moveToChild_grid',
        'mobilegridcell_62': 'menuHeadingManagePage_mobilegridcell_62',
        'moveToChild_button': 'menuHeadingManagePage_moveToChild_button',
        'mobilegridcell_63': 'menuHeadingManagePage_mobilegridcell_63',
        'moveToChild_cancel': 'menuHeadingManagePage_moveToChild_cancel'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["menuHeadingManagePage_itemAddButton_onclick_mapping_1"] = {
        "homeScreen": "menuHeadingManagePage",
        "directions": [
            {
                "from_name": "currentItem",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuHeadingManagePage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['description']",
                        "target": "$['headingDescriptionField:text']"
                    },
                    {
                        "source": "$['heading']",
                        "target": "$['headingAddField:text']"
                    }
                ]
            },
            {
                "from_name": "headingSelectList",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuHeadingManagePage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$[i]['id']",
                        "target": "$['headingParentSelect-0:value']"
                    },
                    {
                        "source": "$[i]",
                        "target": "$['headingParentSelect-0']"
                    },
                    {
                        "source": "$[i]['heading']",
                        "target": "$['headingParentSelect-0:label']"
                    }
                ]
            },
            {
                "from_name": "selectedParentItem",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuHeadingManagePage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$",
                        "target_transformation": function(value, element) {
                            if (value) {
                                return value.id;
                            } else {
                                return getRootId('headingSelectList');
                            }
                        },
                        "target": "$['headingParentSelect:selectedMenuItem']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["menuHeadingManagePage_headingItem_ontaphold_mapping_3"] = {
        "homeScreen": "menuHeadingManagePage",
        "directions": [
            {
                "from_name": "currentItem",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuHeadingManagePage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['heading']",
                        "target": "$['headingAddField:text']"
                    },
                    {
                        "source": "$['description']",
                        "target": "$['headingDescriptionField:text']"
                    },
                    {
                        "source": "$['parent_id']",
                        "target": "$['headingParentSelect:selectedMenuItem']"
                    }
                ]
            },
            {
                "from_name": "headingSelectList",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuHeadingManagePage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$[i]",
                        "target": "$['headingParentSelect-0']"
                    },
                    {
                        "source": "$[i]['heading']",
                        "target": "$['headingParentSelect-0:label']"
                    },
                    {
                        "source": "$[i]['id']",
                        "target": "$['headingParentSelect-0:value']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["menuHeadingManagePage_headingItem_ontaphold_mapping_4"] = {
        "homeScreen": "menuHeadingManagePage",
        "directions": [
            {
                "from_name": "currentItem",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuHeadingManagePage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['parent_id']",
                        "target": "$['headingParentSelect:selectedMenuItem']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["menuHeadingManagePage_menuHeading_list_service_onsuccess_mapping_0"] = {
        "homeScreen": "menuHeadingManagePage",
        "directions": [
            {
                "from_name": "menuHeading_list_service",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "menuHeading",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['body'][i]['headingParent']['_id']",
                        "target": "$[i]['parent_id']"
                    },
                    {
                        "source": "$['body'][i]['_id']",
                        "target": "$[i]['id']"
                    },
                    {
                        "source": "$['body'][i]['heading']",
                        "target": "$[i]['heading']"
                    },
                    {
                        "source": "$['body'][i]['headingDescription']",
                        "target": "$[i]['description']"
                    },
                    {
                        "source": "$['body'][i]['headingParent']['price']",
                        "target": "$[i]['price']"
                    },
                    {
                        "source": "$['body'][i]['order']",
                        "target": "$[i]['order']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["menuHeadingManagePage_menuHeading_list_service_onsuccess_mapping_2"] = {
        "homeScreen": "menuHeadingManagePage",
        "directions": [
            {
                "from_name": "menuHierarchyList",
                "from_type": "VARIABLE_STORAGE",
                "to_name": "menuHeadingManagePage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$[i]",
                        "target_transformation": function(value, element) {
                            element.prop('item_id', value.id);
                            //console.log(JSON.stringify(value));
                            //console.log(element);
                        },
                        "target": "$['headingItem']"
                    },
                    {
                        "source": "$[i]['visible']",
                        "target": "$['headingItem:visible']"
                    },
                    {
                        "source": "$[i]['heading']",
                        "target": "$['headingItem:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["menuHeadingManagePage_menuHeading_list_service_onbeforesend_mapping_0"] = {
        "homeScreen": "menuHeadingManagePage",
        "directions": [
            {
                "from_name": "sessionToken",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuHeading_list_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}"
                    },
                    "parameters": {
                        "include": "vendor,vendor.state,vendor.country,headingParent,headingParent.vendor,headingParent.vendor.state,headingParent.vendor.country,headingParent.headingParent,headingParent.headingParent.vendor,headingParent.headingParent.vendor.state,headingParent.headingParent.vendor.country,headingParent.headingParent.headingParent,headingParent.headingParent.headingParent.vendor,headingParent.headingParent.headingParent.vendor.state,headingParent.headingParent.headingParent.vendor.country,headingParent.headingParent.headingParent.headingParent,headingParent.headingParent.headingParent.headingParent.vendor,headingParent.headingParent.headingParent.headingParent.headingParent",
                        "sort": "order",
                        "where": " {\"vendor\": {\"$inQuery\" : { \"_id\": \"{vendor_id}\"}}}",
                        "limit": "1500"
                    },
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['headers']['X-Appery-Session-Token']"
                    }
                ]
            }
        ]
    };

    Apperyio.mappings["menuHeadingManagePage_genericMapService_onsuccess_mapping_0"] = {
        "homeScreen": "menuHeadingManagePage",
        "directions": [
            {
                "from_name": "menuHierarchyList",
                "from_type": "VARIABLE_STORAGE",
                "to_name": "menuHeadingManagePage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$[i]",
                        "target_transformation": function(value, element) {
                            return mapMenuItem(value, element);
                        },
                        "target": "$['headingItem']"
                    },
                    {
                        "source": "$[i]['visible']",
                        "target": "$['headingItem:visible']"
                    },
                    {
                        "source": "$[i]['description']",
                        "target_transformation": function(value, element) {
                            return value || '';
                        },
                        "target": "$['headingItem']['menuHeadingDescription:text']"
                    },
                    {
                        "source": "$[i]['price']",
                        "target_transformation": function(value, element) {
                            if (value) {
                                return value.toFixed(2);
                            } else {
                                return "";
                            }
                        },
                        "target": "$['headingItem']['price:text']"
                    },
                    {
                        "source": "$[i]['isHidden']",
                        "target_transformation": function(value, element) {
                            return getItemStatus(value);
                        },
                        "target": "$['headingItem']['hiddenStatus:text']"
                    },
                    {
                        "source": "$[i]['isItem']",
                        "target": "$['headingItem']['hiddenStatus:visible']"
                    },
                    {
                        "source": "$[i]['isItem']",
                        "target": "$['headingItem']['priceGrid:visible']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["menuHeadingManagePage_menuHeading_create_service_onbeforesend_mapping_0"] = {
        "homeScreen": "menuHeadingManagePage",
        "directions": [
            {
                "from_name": "menuHeadingManagePage",
                "from_type": "UI",
                "to_name": "menuHeading_create_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": {
                        "vendor": {
                            "collName": "vendor"
                        },
                        "headingParent": {
                            "collName": "menuHeading"
                        },
                        "acl": {
                            "*": {
                                "write": true,
                                "read": true
                            }
                        },
                        "vend": {
                            "collName": "_users",
                            "_id": "{user_id}"
                        }
                    }
                },
                "mappings": [
                    {
                        "source": "$['headingAddField:text']",
                        "target": "$['body']['heading']"
                    },
                    {
                        "source": "$['headingParentSelect:selectedMenuItem']",
                        "target": "$['body']['headingParent']['_id']"
                    },
                    {
                        "source": "$['headingDescriptionField:text']",
                        "target": "$['body']['headingDescription']"
                    },
                    {
                        "source": "$['headingParentSelect:selectedMenuItem']",
                        "target_transformation": function(value) {
                            if (!value) {
                                return null;
                            }
                            return {
                                collName: 'menuHeading',
                                _id: value
                            };
                        },
                        "target": "$['body']['headingParent']"
                    },
                    {
                        "source": "$['headingParentSelect:selectedMenuItem']",
                        "target_transformation": function(value) {
                            return getNewOrder(value);
                        },
                        "target": "$['body']['order']"
                    }
                ]
            },
            {
                "from_name": "vendorId",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuHeading_create_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": {
                        "vendor": {
                            "collName": "vendor"
                        },
                        "headingParent": {
                            "collName": "menuHeading"
                        },
                        "acl": {
                            "*": {
                                "write": true,
                                "read": true
                            }
                        },
                        "vend": {
                            "collName": "_users",
                            "_id": "{user_id}"
                        }
                    }
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['body']['vendor']['_id']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["menuHeadingManagePage_mapMenuHedingItemService_onsuccess_mapping_0"] = {
        "homeScreen": "menuHeadingManagePage",
        "directions": [
            {
                "from_name": "currentItem",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuHeadingManagePage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['heading']",
                        "target": "$['headingAddField:text']"
                    },
                    {
                        "source": "$['description']",
                        "target": "$['headingDescriptionField:text']"
                    }
                ]
            },
            {
                "from_name": "menuHierarchyList",
                "from_type": "VARIABLE_STORAGE",
                "to_name": "menuHeadingManagePage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$[i]",
                        "target_transformation": function(value, element) {
                            if (value.isItem) {
                                return false;
                            }
                            return value;
                        },
                        "target": "$['headingParentSelect-0']"
                    },
                    {
                        "source": "$[i]['id']",
                        "target": "$['headingParentSelect-0:value']"
                    },
                    {
                        "source": "$[i]['heading']",
                        "target": "$['headingParentSelect-0:label']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["menuHeadingManagePage_mapMenuHedingItemService_onbeforesend_mapping_0"] = {
        "homeScreen": "menuHeadingManagePage",
        "directions": [
            {
                "to_name": "mapMenuHedingItemService",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": null
                },
                "mappings": []
            }
        ]
    };
    Apperyio.mappings["menuHeadingManagePage_menuHeading_update_service_onbeforesend_mapping_0"] = {
        "homeScreen": "menuHeadingManagePage",
        "directions": [
            {
                "from_name": "currentItem",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuHeading_update_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": {
                        "headingParent": {
                            "collName": "menuHeading"
                        },
                        "acl": {
                            "*": {
                                "write": true,
                                "read": true
                            }
                        }
                    }
                },
                "mappings": [
                    {
                        "source": "$['id']",
                        "target": "$['parameters']['_id']"
                    },
                    {
                        "source": "$['order']",
                        "target": "$['body']['order']"
                    }
                ]
            },
            {
                "from_name": "menuHeadingManagePage",
                "from_type": "UI",
                "to_name": "menuHeading_update_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": {
                        "headingParent": {
                            "collName": "menuHeading"
                        },
                        "acl": {
                            "*": {
                                "write": true,
                                "read": true
                            }
                        }
                    }
                },
                "mappings": [
                    {
                        "source": "$['headingDescriptionField:text']",
                        "target": "$['body']['headingDescription']"
                    },
                    {
                        "source": "$['headingAddField:text']",
                        "target": "$['body']['heading']"
                    },
                    {
                        "source": "$['headingParentSelect:selectedMenuItem']",
                        "target": "$['body']['headingParent']['_id']"
                    }
                ]
            },
            {
                "from_name": "sessionToken",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuHeading_update_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": {
                        "headingParent": {
                            "collName": "menuHeading"
                        },
                        "acl": {
                            "*": {
                                "write": true,
                                "read": true
                            }
                        }
                    }
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['headers']['X-Appery-Session-Token']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["menuHeadingManagePage_menuHeading_updateOrder_service_onbeforesend_mapping_0"] = {
        "homeScreen": "menuHeadingManagePage",
        "directions": [
            {
                "from_name": "arrayOfObjects",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuHeading_updateOrder_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "Content-Type": "application/json"
                    },
                    "parameters": {
                        "collection": "item"
                    },
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$[i]",
                        "target": "$['body'][i]"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["menuHeadingManagePage_menuHeading_delete_service_onbeforesend_mapping_0"] = {
        "homeScreen": "menuHeadingManagePage",
        "directions": [
            {
                "from_name": "selectedItem",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuHeading_delete_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['_id']"
                    }
                ]
            },
            {
                "from_name": "sessionToken",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuHeading_delete_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['headers']['X-Appery-Session-Token']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["menuHeadingManagePage_menuHeading_createMenuHeading_service_onbeforesend_mapping_0"] = {
        "homeScreen": "menuHeadingManagePage",
        "directions": [
            {
                "from_name": "vendorId",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuHeading_createMenuHeading_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "Content-Type": "text/plain",
                        "X-Appery-Session-Token": "{session_token}"
                    },
                    "parameters": {
                        "order": "1",
                        "description": "dd",
                        "vendorId": "5714a09ce4b06624d2ed6c8f",
                        "heading": "A TEST TEST HEADING 1"
                    },
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['vendorId']"
                    }
                ]
            },
            {
                "from_name": "menuHeadingManagePage",
                "from_type": "UI",
                "to_name": "menuHeading_createMenuHeading_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "Content-Type": "text/plain",
                        "X-Appery-Session-Token": "{session_token}"
                    },
                    "parameters": {
                        "order": "1",
                        "description": "dd",
                        "vendorId": "5714a09ce4b06624d2ed6c8f",
                        "heading": "A TEST TEST HEADING 1"
                    },
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$['headingAddField:text']",
                        "target": "$['parameters']['heading']"
                    },
                    {
                        "source": "$['headingDescriptionField:text']",
                        "target": "$['parameters']['description']"
                    },
                    {
                        "source": "$['headingParentSelect:selectedMenuItem']",
                        "target": "$['parameters']['parentId']"
                    },
                    {
                        "source": "$['headingParentSelect:selectedMenuItem']",
                        "target_transformation": function(value) {
                            return getNewOrder(value);
                        },
                        "target": "$['parameters']['order']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["menuHeadingManagePage_menuHeading_getMenuHierarchy_service_onsuccess_mapping_0"] = {
        "homeScreen": "menuHeadingManagePage",
        "directions": [
            {
                "from_name": "menuHeading_getMenuHierarchy_service",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "menuHierarchyList",
                "to_type": "VARIABLE_STORAGE",
                "mappings": [
                    {
                        "source": "$['body'][i]['level']",
                        "target": "$[i]['level']"
                    },
                    {
                        "source": "$['body'][i]['order']",
                        "target": "$[i]['order']"
                    },
                    {
                        "source": "$['body'][i]['opened']",
                        "target": "$[i]['opened']"
                    },
                    {
                        "source": "$['body'][i]['description']",
                        "target": "$[i]['description']"
                    },
                    {
                        "source": "$['body'][i]['heading']",
                        "target": "$[i]['heading']"
                    },
                    {
                        "source": "$['body'][i]['_id']",
                        "target": "$[i]['id']"
                    },
                    {
                        "source": "$['body'][i]['parent']['_id']",
                        "target": "$[i]['parent_id']"
                    },
                    {
                        "source": "$['body'][i]['visible']",
                        "target": "$[i]['visible']"
                    },
                    {
                        "source": "$['body'][i]['hidden']",
                        "target": "$[i]['isHidden']"
                    },
                    {
                        "source": "$['body'][i]['isItem']",
                        "target": "$[i]['isItem']"
                    },
                    {
                        "source": "$['body'][i]['hasChildren']",
                        "target": "$[i]['hasChildren']"
                    },
                    {
                        "source": "$['body'][i]['price']",
                        "target": "$[i]['price']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["menuHeadingManagePage_menuHeading_getMenuHierarchy_service_onbeforesend_mapping_0"] = {
        "homeScreen": "menuHeadingManagePage",
        "directions": [
            {
                "from_name": "vendorId",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuHeading_getMenuHierarchy_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "Content-Type": "application/json"
                    },
                    "parameters": {
                        "vendorId": "{vendor_id}",
                        "openAll": "true",
                        "onlyHeading": "false",
                        "profileUseToggle": "off",
                        "hideEmpty": "off",
                        "cache": "off"
                    },
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['vendorId']"
                    }
                ]
            },
            {
                "from_name": "sessionToken",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuHeading_getMenuHierarchy_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "Content-Type": "application/json"
                    },
                    "parameters": {
                        "vendorId": "{vendor_id}",
                        "openAll": "true",
                        "onlyHeading": "false",
                        "profileUseToggle": "off",
                        "hideEmpty": "off",
                        "cache": "off"
                    },
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['headers']['X-Appery-Session-Token']"
                    }
                ]
            },
            {
                "from_name": "useMenuCache",
                "from_type": "VARIABLE_STORAGE",
                "to_name": "menuHeading_getMenuHierarchy_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "Content-Type": "application/json"
                    },
                    "parameters": {
                        "vendorId": "{vendor_id}",
                        "openAll": "true",
                        "onlyHeading": "false",
                        "profileUseToggle": "off",
                        "hideEmpty": "off",
                        "cache": "off"
                    },
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['cache']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["menuHeadingManagePage_menuHeading_updateMenuCache_service_onsuccess_mapping_0"] = {
        "homeScreen": "menuHeadingManagePage",
        "directions": []
    };
    Apperyio.mappings["menuHeadingManagePage_menuHeading_updateMenuCache_service_onbeforesend_mapping_0"] = {
        "homeScreen": "menuHeadingManagePage",
        "directions": [
            {
                "from_name": "vendorId",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuHeading_updateMenuCache_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "Content-Type": "text/plain",
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['vendorId']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["menuHeadingManagePage_menuHeading_updateParent_service_onbeforesend_mapping_0"] = {
        "homeScreen": "menuHeadingManagePage",
        "directions": [
            {
                "to_name": "menuHeading_updateParent_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "Content-Type": "text/plain"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": []
            }
        ]
    };
    Apperyio.mappings["menuHeadingManagePage_menuHeading_updateHeadingParentSelect_service_onsuccess_mapping_0"] = {
        "homeScreen": "menuHeadingManagePage",
        "directions": [
            {
                "from_name": "headingSelectList",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuHeadingManagePage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$[i]",
                        "target": "$['headingParentSelect-0']"
                    },
                    {
                        "source": "$[i]['id']",
                        "target": "$['headingParentSelect-0:value']"
                    },
                    {
                        "source": "$[i]['heading']",
                        "target": "$['headingParentSelect-0:label']"
                    }
                ]
            },
            {
                "from_name": "currentItem",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuHeadingManagePage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['parent_id']",
                        "target": "$['headingParentSelect:selectedMenuItem']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.menuHeading_list_service = Apperyio.datasources.menuHeading_list_service = new Apperyio.DataSource(projectMdb1_menuHeading_list_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["menuHeadingManagePage_menuHeading_list_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["menuHeadingManagePage_menuHeading_list_service_onsuccess_mapping_0"]);
            //console.log(data);
            //sessionStorage.setItem("menuItemsList", data);
            // storageSet("menuItemsList", data);
            makeHierarchy(true);
            try {
                genericMapService.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.genericMapService = Apperyio.datasources.genericMapService = new Apperyio.DataSource(GenericService, {
        "onBeforeSend": function(jqXHR) {},
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["menuHeadingManagePage_genericMapService_onsuccess_mapping_0"]);
            /*
            var scrollTo = storageGet('scrollTo');
            if(scrollTo)
            {
            	window.scrollTo(0, scrollTo);
            }
            storageSet('scrollTo', 0);
            */
            ;
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.menuHeading_create_service = Apperyio.datasources.menuHeading_create_service = new Apperyio.DataSource(projectMdb1_menuHeading_create_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["menuHeadingManagePage_menuHeading_create_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio('headingAddPopup').popup('close');
            try {
                menuHeading_list_service.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
            try {
                menuHeading_updateMenuCache_service.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.mapMenuHedingItemService = Apperyio.datasources.mapMenuHedingItemService = new Apperyio.DataSource(mapMenuHedingItemGenericService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["menuHeadingManagePage_mapMenuHedingItemService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["menuHeadingManagePage_mapMenuHedingItemService_onsuccess_mapping_0"]);
            Apperyio("headingParentSelect").val(currentItem.parent_id).refresh();
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.menuHeading_update_service = Apperyio.datasources.menuHeading_update_service = new Apperyio.DataSource(projectMdb1_menuHeading_update_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["menuHeadingManagePage_menuHeading_update_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio('headingAddPopup').popup('close');
            menuHeading_updateMenuCache_service.execute({});
            try {
                menuHeading_getMenuHierarchy_service.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.menuHeading_updateOrder_service = Apperyio.datasources.menuHeading_updateOrder_service = new Apperyio.DataSource(updateOrder_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["menuHeadingManagePage_menuHeading_updateOrder_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            try {
                menuHeading_getMenuHierarchy_service.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.menuHeading_delete_service = Apperyio.datasources.menuHeading_delete_service = new Apperyio.DataSource(projectMdb1_menuHeading_delete_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["menuHeadingManagePage_menuHeading_delete_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio('headingAddPopup').popup('close');
            try {
                menuHeading_getMenuHierarchy_service.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.menuHeading_createMenuHeading_service = Apperyio.datasources.menuHeading_createMenuHeading_service = new Apperyio.DataSource(createMenuHeading_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["menuHeadingManagePage_menuHeading_createMenuHeading_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio('headingAddPopup').popup('close');
            menuHeading_updateMenuCache_service.execute({});
            try {
                menuHeading_getMenuHierarchy_service.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.menuHeading_getMenuHierarchy_service = Apperyio.datasources.menuHeading_getMenuHierarchy_service = new Apperyio.DataSource(getMenuHierarchy_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["menuHeadingManagePage_menuHeading_getMenuHierarchy_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["menuHeadingManagePage_menuHeading_getMenuHierarchy_service_onsuccess_mapping_0"]);
            try {
                genericMapService.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
            try {
                $a.storage["useMenuCache"].update("$", "off")
            } catch (e) {
                console.error(e)
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            alert('Problem updating menu cache');
        }
    });
    window.menuHeading_updateMenuCache_service = Apperyio.datasources.menuHeading_updateMenuCache_service = new Apperyio.DataSource(updateMenuCache_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["menuHeadingManagePage_menuHeading_updateMenuCache_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["menuHeadingManagePage_menuHeading_updateMenuCache_service_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.menuHeading_updateParent_service = Apperyio.datasources.menuHeading_updateParent_service = new Apperyio.DataSource(updateParent_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["menuHeadingManagePage_menuHeading_updateParent_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            try {
                menuHeading_getMenuHierarchy_service.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.menuHeading_updateHeadingParentSelect_service = Apperyio.datasources.menuHeading_updateHeadingParentSelect_service = new Apperyio.DataSource(GenericService, {
        "onBeforeSend": function(jqXHR) {},
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["menuHeadingManagePage_menuHeading_updateHeadingParentSelect_service_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'menuHeadingManagePage';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var menuHeadingManagePage_onLoad = function() {
        menuHeadingManagePage_elementsExtraJS();
        menuHeadingManagePage_deviceEvents();
        menuHeadingManagePage_windowEvents();
        menuHeadingManagePage_elementsEvents();
    };
    // screen window events
    function menuHeadingManagePage_windowEvents() {
        $('#menuHeadingManagePage').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#menuHeadingManagePage').on({
            pageshow: function(event) {
                /* Call getMenuHierarchy service */
                Apperyio('headingManageHeader').parents('[data-role=header]').addClass('fixed-header');
                //if(!(storageGet('menuHierarchyList') && storageGet('menuHierarchyList').length))
                storageSet('useMenuCache', 'off');
                menuHeading_getMenuHierarchy_service.execute({});
                // reset itemToMove
                menuHeadingManager.resetItemToMove();;
                try {
                    genericMapService.execute({});
                } catch (e) {
                    console.error(e);
                    hideSpinner();
                };
            },
        });
    };
    // device events
    function menuHeadingManagePage_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function menuHeadingManagePage_elementsExtraJS() {
        // screen (menuHeadingManagePage) extra code
        /* menuList */
        listView = $("#menuHeadingManagePage_menuList");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#menuHeadingManagePage_menuList .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        /* headingItem */
        /* headingAddPopup */
        $("#menuHeadingManagePage_headingAddPopup").popup("option", "positionTo", "window");
        /* headingParentSelect */
        $("#menuHeadingManagePage_headingParentSelect").parent().find("a.ui-btn").attr("tabindex", "5");
        /* categoryEditPopup */
        $("#menuHeadingManagePage_categoryEditPopup").popup("option", "positionTo", "window");
        /* categoryParentEditButton */
        $("#menuHeadingManagePage_categoryParentEditButton").parent().find("a.ui-btn").attr("tabindex", "7");
        /* deleteHeadingConfirmPopup */
        $("#menuHeadingManagePage_deleteHeadingConfirmPopup").popup("option", "positionTo", "window");
        /* moveFrom_popup */
        $("#menuHeadingManagePage_moveFrom_popup").popup("option", "positionTo", "window");
        /* moveToOrder_popup */
        $("#menuHeadingManagePage_moveToOrder_popup").popup("option", "positionTo", "window");
        /* moveToChild_popup */
        $("#menuHeadingManagePage_moveToChild_popup").popup("option", "positionTo", "window");
    };
    // screen elements handler
    function menuHeadingManagePage_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#menuHeadingManagePage_headingManageHeader [name="homeButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('proprietorStartPage', {
                        transition: 'slidedown',
                        reverse: false
                    });
                }
            },
        }, '#menuHeadingManagePage_headingManageHeader [name="homeButton"]');
        $(document).off("click", '#menuHeadingManagePage_menuHeadingContainer [name="itemAddButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    editMode = false;
                    storageSet('currentItem', {});
                    setDefaultSelectedItem('headingParentSelect');
                    Apperyio('deleteButton').hide();
                    Apperyio('headingAddError').hide();
                    makeHierarchy();
                    Apperyio.processMappingAction(Apperyio.mappings["menuHeadingManagePage_itemAddButton_onclick_mapping_1"]);
                    var popupElement = Apperyio("headingAddPopup");
                    if (popupElement.popup("option", "positionTo") === "origin") {
                        popupElement.popup("open", {
                            transition: "pop",
                            positionTo: "#" + $(this).attr("id")
                        });
                    } else {
                        popupElement.popup("open", {
                            transition: "pop"
                        });
                    };
                }
            },
        }, '#menuHeadingManagePage_menuHeadingContainer [name="itemAddButton"]');
        $(document).off("click", '#menuHeadingManagePage_menuHeadingContainer [name="expandCollapseAllButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    collapseExpandAll();
                    genericMapService.execute({});
                }
            },
        }, '#menuHeadingManagePage_menuHeadingContainer [name="expandCollapseAllButton"]');
        $(document).off("click", '#menuHeadingManagePage_menuHeadingContainer [name="menuPreviewButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    preview = true;
                    Apperyio.navigateTo('menuPage_v2', {
                        reverse: false
                    });
                }
            },
        }, '#menuHeadingManagePage_menuHeadingContainer [name="menuPreviewButton"]');
        $(document).off("swipeleft taphold click swiperight", '#menuHeadingManagePage_menuHeadingContainer [name="headingItem"]').on({
            swipeleft: function(event) {
                /* Left Swipe opens Move as Child */
                menuHeadingManager.swipeLeft(this);
            },
            taphold: function(event) {
                menuHeadingManagePageBuilder.itemTaphold(this);
            },
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    /* Open/close menu branch */
                    currentItem = _.findWhere(storageGet('menuHierarchyList'), {
                        id: $(this).attr('item_id')
                    });
                    storageSet('currentItem', currentItem);
                    console.log('--- click item:', currentItem);
                    onClickMenuItem(this);
                    return false;
                    /*
                    Apperyio.storage.selectedItem.set(this.item_id);
                    currentItem = this;

                    mapMenuHedingItemService.execute({});
                    //Apperyio("headingParentSelect").val(hierarchyList[0].id).refresh();
                    console.log(editMode);
                    Apperyio("headingAddPopup").popup("open");
                    */
                    ;
                }
            },
            swiperight: function(event) {
                /* Right Swipe opens Mark or Reorder */
                menuHeadingManager.swipeRight(this);
            },
        }, '#menuHeadingManagePage_menuHeadingContainer [name="headingItem"]');
        $(document).off("click", '#menuHeadingManagePage_headingAddPopup [name="headingAddSaveButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    createOrUpdateHeading();
                }
            },
        }, '#menuHeadingManagePage_headingAddPopup [name="headingAddSaveButton"]');
        $(document).off("click", '#menuHeadingManagePage_headingAddPopup [name="deleteButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('headingAddPopup').popup('close');
                    setTimeout(function() {
                        Apperyio('deleteHeadingConfirmPopup').popup('open');
                    }, 100);
                }
            },
        }, '#menuHeadingManagePage_headingAddPopup [name="deleteButton"]');
        $(document).off("click", '#menuHeadingManagePage_categoryEditPopup [name="categoryEditSaveButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('categoryEditPopup').popup('close');
                }
            },
        }, '#menuHeadingManagePage_categoryEditPopup [name="categoryEditSaveButton"]');
        $(document).off("click", '#menuHeadingManagePage_categoryEditPopup [name="headingCancelButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('categoryEditPopup').popup('close');
                }
            },
        }, '#menuHeadingManagePage_categoryEditPopup [name="headingCancelButton"]');
        $(document).off("click", '#menuHeadingManagePage_deleteHeadingConfirmPopup [name="deleteConfirmButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        menuHeading_delete_service.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                    Apperyio('deleteHeadingConfirmPopup').popup('close');
                }
            },
        }, '#menuHeadingManagePage_deleteHeadingConfirmPopup [name="deleteConfirmButton"]');
        $(document).off("click", '#menuHeadingManagePage_deleteHeadingConfirmPopup [name="deleteCancelButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('deleteHeadingConfirmPopup').popup('close');
                    setTimeout(function() {
                        Apperyio('headingAddPopup').popup('open');
                    }, 100);
                }
            },
        }, '#menuHeadingManagePage_deleteHeadingConfirmPopup [name="deleteCancelButton"]');
        $(document).off("click", '#menuHeadingManagePage_moveFrom_popup [name="moveFrom_button"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('moveFrom_popup').popup('close');
                }
            },
        }, '#menuHeadingManagePage_moveFrom_popup [name="moveFrom_button"]');
        $(document).off("click", '#menuHeadingManagePage_moveFrom_popup [name="moveFrom_cancel"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('moveFrom_popup').popup('close');
                    /* Reset item to be moved */
                    menuHeadingManager.resetItemToMove();
                }
            },
        }, '#menuHeadingManagePage_moveFrom_popup [name="moveFrom_cancel"]');
        $(document).off("click", '#menuHeadingManagePage_moveToOrder_popup [name="moveToBefore_button"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('moveToOrder_popup').popup('close');
                    menuHeadingManager.moveBefore();
                }
            },
        }, '#menuHeadingManagePage_moveToOrder_popup [name="moveToBefore_button"]');
        $(document).off("click", '#menuHeadingManagePage_moveToOrder_popup [name="moveToAfter_button"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('moveToOrder_popup').popup('close');
                    menuHeadingManager.moveAfter();
                }
            },
        }, '#menuHeadingManagePage_moveToOrder_popup [name="moveToAfter_button"]');
        $(document).off("click", '#menuHeadingManagePage_moveToOrder_popup [name="moveTo_cancel"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('moveToOrder_popup').popup('close');
                    /* Reset itemToMove */
                    menuHeadingManager.resetItemToMove();
                }
            },
        }, '#menuHeadingManagePage_moveToOrder_popup [name="moveTo_cancel"]');
        $(document).off("click", '#menuHeadingManagePage_moveToChild_popup [name="moveToChild_button"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('moveToChild_popup').popup('close');
                    menuHeadingManager.moveToChild();
                }
            },
        }, '#menuHeadingManagePage_moveToChild_popup [name="moveToChild_button"]');
        $(document).off("click", '#menuHeadingManagePage_moveToChild_popup [name="moveToChild_cancel"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('moveToChild_popup').popup('close');
                    menuHeadingManager.resetItemToMove();
                }
            },
        }, '#menuHeadingManagePage_moveToChild_popup [name="moveToChild_cancel"]');
    };
    $(document).off("pagebeforeshow", "#menuHeadingManagePage").on("pagebeforeshow", "#menuHeadingManagePage", function(event, ui) {
        Apperyio.CurrentScreen = "menuHeadingManagePage";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    menuHeadingManagePage_onLoad();
};
$(document).off("pagecreate", "#menuHeadingManagePage").on("pagecreate", "#menuHeadingManagePage", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    menuHeadingManagePage_js();
});