/*
 * JS for operationsRestaurantPage generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '148444cb-eb26-4cec-bc22-29bf794bc529';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "aboutPage",
    "location": "aboutPage.html"
}, {
    "name": "itemDetailsPage",
    "location": "itemDetailsPage.html"
}, {
    "name": "menuHeadingManagePage",
    "location": "menuHeadingManagePage.html"
}, {
    "name": "proprietorAnalyticsPage",
    "location": "proprietorAnalyticsPage.html"
}, {
    "name": "zzpromoEdit",
    "location": "zzpromoEdit.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "itemPage",
    "location": "itemPage.html"
}, {
    "name": "zzpromoManage",
    "location": "zzpromoManage.html"
}, {
    "name": "zzscannerPage",
    "location": "zzscannerPage.html"
}, {
    "name": "zztimeRangePage",
    "location": "zztimeRangePage.html"
}, {
    "name": "selectedPage",
    "location": "selectedPage.html"
}, {
    "name": "zzCSStestPage",
    "location": "zzCSStestPage.html"
}, {
    "name": "zzmenuPage",
    "location": "zzmenuPage.html"
}, {
    "name": "menuHistoryPage",
    "location": "menuHistoryPage.html"
}, {
    "name": "faqPage",
    "location": "faqPage.html"
}, {
    "name": "zzratingInfoPage",
    "location": "zzratingInfoPage.html"
}, {
    "name": "orderHistoryPage",
    "location": "orderHistoryPage.html"
}, {
    "name": "createAccount",
    "location": "createAccount.html"
}, {
    "name": "itemManagePage",
    "location": "itemManagePage.html"
}, {
    "name": "proprietorStartPage",
    "location": "proprietorStartPage.html"
}, {
    "name": "operationsRestaurantPage",
    "location": "operationsRestaurantPage.html"
}, {
    "name": "zzdetailedReviewPage",
    "location": "zzdetailedReviewPage.html"
}, {
    "name": "itemEditPage",
    "location": "itemEditPage.html"
}, {
    "name": "selectionHistoryPage",
    "location": "selectionHistoryPage.html"
}, {
    "name": "zzproprietorStatPage",
    "location": "zzproprietorStatPage.html"
}, {
    "name": "zzitemInventoryPage",
    "location": "zzitemInventoryPage.html"
}, {
    "name": "zzalertPage",
    "location": "zzalertPage.html"
}, {
    "name": "zzsearchPage",
    "location": "zzsearchPage.html"
}, {
    "name": "menuPage_v2",
    "location": "menuPage_v2.html"
}, {
    "name": "zzqrCodePage",
    "location": "zzqrCodePage.html"
}, {
    "name": "profilePage",
    "location": "profilePage.html"
}, {
    "name": "filterPage",
    "location": "filterPage.html"
}, {
    "name": "easterEggPage",
    "location": "easterEggPage.html"
}, {
    "name": "helpPage",
    "location": "helpPage.html"
}, {
    "name": "navigatePage",
    "location": "navigatePage.html"
}, {
    "name": "menuPreviewPage",
    "location": "menuPreviewPage.html"
}, {
    "name": "zzfacebookLogin",
    "location": "zzfacebookLogin.html"
}, {
    "name": "menu_shared",
    "location": "menu_shared.html"
}, {
    "name": "logoutPage",
    "location": "logoutPage.html"
}, {
    "name": "favoritesPage",
    "location": "favoritesPage.html"
}, {
    "name": "proprietorPage",
    "location": "proprietorPage.html"
}, {
    "name": "wishListPage",
    "location": "wishListPage.html"
}, {
    "name": "menuManagementPage",
    "location": "menuManagementPage.html"
}, {
    "name": "touPage",
    "location": "touPage.html"
}, {
    "name": "zzsettingsPage",
    "location": "zzsettingsPage.html"
}];

function operationsRestaurantPage_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'homeButton': 'operationsRestaurantPage_homeButton',
        'changeLoginPasswordGrid': 'operationsRestaurantPage_changeLoginPasswordGrid',
        'loginChangeCell': 'operationsRestaurantPage_loginChangeCell',
        'loginChangeButton': 'operationsRestaurantPage_loginChangeButton',
        'passwordChangeCell': 'operationsRestaurantPage_passwordChangeCell',
        'passwordChangeButton': 'operationsRestaurantPage_passwordChangeButton',
        'typeLabel': 'operationsRestaurantPage_typeLabel',
        'selectBusinessTypeButton': 'operationsRestaurantPage_selectBusinessTypeButton',
        'selectBusinessTypeButton-0': 'operationsRestaurantPage_selectBusinessTypeButton-0',
        'copyMenuLinkButton': 'operationsRestaurantPage_copyMenuLinkButton',
        'locationLabel': 'operationsRestaurantPage_locationLabel',
        'businessName': 'operationsRestaurantPage_businessName',
        'streetAddress1': 'operationsRestaurantPage_streetAddress1',
        'streetAddress2': 'operationsRestaurantPage_streetAddress2',
        'city': 'operationsRestaurantPage_city',
        'stateGrid': 'operationsRestaurantPage_stateGrid',
        'statelabelCell': 'operationsRestaurantPage_statelabelCell',
        'stateLabel': 'operationsRestaurantPage_stateLabel',
        'stateDropdownCell': 'operationsRestaurantPage_stateDropdownCell',
        'stateDropdown': 'operationsRestaurantPage_stateDropdown',
        'stateDropdown-0': 'operationsRestaurantPage_stateDropdown-0',
        'stateDropdown1': 'operationsRestaurantPage_stateDropdown1',
        'zip': 'operationsRestaurantPage_zip',
        'phone': 'operationsRestaurantPage_phone',
        'website': 'operationsRestaurantPage_website',
        'contactLabel': 'operationsRestaurantPage_contactLabel',
        'contactName': 'operationsRestaurantPage_contactName',
        'contactPhone': 'operationsRestaurantPage_contactPhone',
        'contactEmail': 'operationsRestaurantPage_contactEmail',
        'chefHead': 'operationsRestaurantPage_chefHead',
        'vendorDetails': 'operationsRestaurantPage_vendorDetails',
        'vendorDescription': 'operationsRestaurantPage_vendorDescription',
        'hoursLabel': 'operationsRestaurantPage_hoursLabel',
        'hoursGrid': 'operationsRestaurantPage_hoursGrid',
        'mondayCell': 'operationsRestaurantPage_mondayCell',
        'mondayLabel': 'operationsRestaurantPage_mondayLabel',
        'mondayOpenCell': 'operationsRestaurantPage_mondayOpenCell',
        'mondayOpen': 'operationsRestaurantPage_mondayOpen',
        'mondayCloseCell': 'operationsRestaurantPage_mondayCloseCell',
        'mondayClose': 'operationsRestaurantPage_mondayClose',
        'tuesdayCell': 'operationsRestaurantPage_tuesdayCell',
        'tuesdayLabel': 'operationsRestaurantPage_tuesdayLabel',
        'tuesdayOpenCell': 'operationsRestaurantPage_tuesdayOpenCell',
        'tuesdayOpen': 'operationsRestaurantPage_tuesdayOpen',
        'tuesdayCloseCell': 'operationsRestaurantPage_tuesdayCloseCell',
        'tuesdayClose': 'operationsRestaurantPage_tuesdayClose',
        'wednesdayCell': 'operationsRestaurantPage_wednesdayCell',
        'wednesdayLabel': 'operationsRestaurantPage_wednesdayLabel',
        'wednesdayOpenCell': 'operationsRestaurantPage_wednesdayOpenCell',
        'wednesdayOpen': 'operationsRestaurantPage_wednesdayOpen',
        'wednesdayCloseCell': 'operationsRestaurantPage_wednesdayCloseCell',
        'wednesdayClose': 'operationsRestaurantPage_wednesdayClose',
        'thursdayCell': 'operationsRestaurantPage_thursdayCell',
        'thursdayLabel': 'operationsRestaurantPage_thursdayLabel',
        'thursdayOpenCell': 'operationsRestaurantPage_thursdayOpenCell',
        'thursdayOpen': 'operationsRestaurantPage_thursdayOpen',
        'thursdayCloseCell': 'operationsRestaurantPage_thursdayCloseCell',
        'thursdayClose': 'operationsRestaurantPage_thursdayClose',
        'fridayCell': 'operationsRestaurantPage_fridayCell',
        'fridayLabel': 'operationsRestaurantPage_fridayLabel',
        'fridayOpenCell': 'operationsRestaurantPage_fridayOpenCell',
        'fridayOpen': 'operationsRestaurantPage_fridayOpen',
        'fridayCloseCell': 'operationsRestaurantPage_fridayCloseCell',
        'fridayClose': 'operationsRestaurantPage_fridayClose',
        'saturdayCell': 'operationsRestaurantPage_saturdayCell',
        'saturdayLabel': 'operationsRestaurantPage_saturdayLabel',
        'saturdayOpenCell': 'operationsRestaurantPage_saturdayOpenCell',
        'saturdayOpen': 'operationsRestaurantPage_saturdayOpen',
        'saturdayCloseCell': 'operationsRestaurantPage_saturdayCloseCell',
        'saturdayClose': 'operationsRestaurantPage_saturdayClose',
        'sundayCell': 'operationsRestaurantPage_sundayCell',
        'sundayLabel': 'operationsRestaurantPage_sundayLabel',
        'sundayOpenCell': 'operationsRestaurantPage_sundayOpenCell',
        'sundayOpen': 'operationsRestaurantPage_sundayOpen',
        'sundayCloseCell': 'operationsRestaurantPage_sundayCloseCell',
        'sundayClose': 'operationsRestaurantPage_sundayClose',
        'taxGrid': 'operationsRestaurantPage_taxGrid',
        'taxLabelCell': 'operationsRestaurantPage_taxLabelCell',
        'taxLabel': 'operationsRestaurantPage_taxLabel',
        'taxFieldCell': 'operationsRestaurantPage_taxFieldCell',
        'taxField': 'operationsRestaurantPage_taxField',
        'mobilegridcell_30': 'operationsRestaurantPage_mobilegridcell_30',
        'percentLabel': 'operationsRestaurantPage_percentLabel',
        'fileSelect': 'operationsRestaurantPage_fileSelect',
        'photoButtonGrid': 'operationsRestaurantPage_photoButtonGrid',
        'addImageButtonCell': 'operationsRestaurantPage_addImageButtonCell',
        'addImageButton': 'operationsRestaurantPage_addImageButton',
        'deleteImageButtonCell': 'operationsRestaurantPage_deleteImageButtonCell',
        'deleteImageButton': 'operationsRestaurantPage_deleteImageButton',
        'placeholderForImageUpload': 'operationsRestaurantPage_placeholderForImageUpload',
        'buttonGridSaveCancel': 'operationsRestaurantPage_buttonGridSaveCancel',
        'operationsInfoSaveCell': 'operationsRestaurantPage_operationsInfoSaveCell',
        'operationsInfoSave': 'operationsRestaurantPage_operationsInfoSave',
        'operationInfoCancelCell': 'operationsRestaurantPage_operationInfoCancelCell',
        'operationInfoCancelButton': 'operationsRestaurantPage_operationInfoCancelButton',
        'deactivateAccountLink': 'operationsRestaurantPage_deactivateAccountLink',
        'mobilegrid_24': 'operationsRestaurantPage_mobilegrid_24',
        'mobilegridcell_25': 'operationsRestaurantPage_mobilegridcell_25',
        'passwordCurrentInput': 'operationsRestaurantPage_passwordCurrentInput',
        'mobilegridcell_27': 'operationsRestaurantPage_mobilegridcell_27',
        'passwordNewInput': 'operationsRestaurantPage_passwordNewInput',
        'passwordConfirmInput': 'operationsRestaurantPage_passwordConfirmInput',
        'errorMessageLabel': 'operationsRestaurantPage_errorMessageLabel',
        'mobilegridcell_29': 'operationsRestaurantPage_mobilegridcell_29',
        'passwordButtonGrid': 'operationsRestaurantPage_passwordButtonGrid',
        'passwordSaveCell': 'operationsRestaurantPage_passwordSaveCell',
        'mobilebutton_23': 'operationsRestaurantPage_mobilebutton_23',
        'passwordCancelCell': 'operationsRestaurantPage_passwordCancelCell',
        'passwordCancelButton': 'operationsRestaurantPage_passwordCancelButton',
        'messageLabel': 'operationsRestaurantPage_messageLabel',
        'popupGrid': 'operationsRestaurantPage_popupGrid',
        'labelCell': 'operationsRestaurantPage_labelCell',
        'emailChangeLable': 'operationsRestaurantPage_emailChangeLable',
        'loginCell': 'operationsRestaurantPage_loginCell',
        'emailField': 'operationsRestaurantPage_emailField',
        'vaildEmailMessage': 'operationsRestaurantPage_vaildEmailMessage',
        'invalidEmailMessage': 'operationsRestaurantPage_invalidEmailMessage',
        'saveCell': 'operationsRestaurantPage_saveCell',
        'changeloginButtonGrid': 'operationsRestaurantPage_changeloginButtonGrid',
        'changeloginSaveCell': 'operationsRestaurantPage_changeloginSaveCell',
        'loginSaveButton': 'operationsRestaurantPage_loginSaveButton',
        'changeloginCancelCell': 'operationsRestaurantPage_changeloginCancelCell',
        'changeloginCancelButton': 'operationsRestaurantPage_changeloginCancelButton',
        'deactivateAccount': 'operationsRestaurantPage_deactivateAccount',
        'deactivateAccountGrid': 'operationsRestaurantPage_deactivateAccountGrid',
        'deactivateAccountConfirmCell': 'operationsRestaurantPage_deactivateAccountConfirmCell',
        'deactivateAccountConfirmButton': 'operationsRestaurantPage_deactivateAccountConfirmButton',
        'deactivateAccountCancelCell': 'operationsRestaurantPage_deactivateAccountCancelCell',
        'deactivateAccountCancelButton': 'operationsRestaurantPage_deactivateAccountCancelButton',
        'mobilelabel_36': 'operationsRestaurantPage_mobilelabel_36',
        'photoDeleteGrid': 'operationsRestaurantPage_photoDeleteGrid',
        'photoDeleteOkCell': 'operationsRestaurantPage_photoDeleteOkCell',
        'photoDeleteOkButton': 'operationsRestaurantPage_photoDeleteOkButton',
        'photoDeleteCancelCell': 'operationsRestaurantPage_photoDeleteCancelCell',
        'photoDeleteCancelButton': 'operationsRestaurantPage_photoDeleteCancelButton'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["operationsRestaurantPage_loginChangeButton_onclick_mapping_0"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": [
            {
                "from_name": "userName",
                "from_type": "SESSION_STORAGE",
                "to_name": "operationsRestaurantPage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['emailField:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["operationsRestaurantPage_passwordChangeButton_onclick_mapping_0"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": [
            {
                "from_name": "userId",
                "from_type": "LOCAL_STORAGE",
                "to_name": "operationsRestaurantPage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$",
                        "target_transformation": function(value, element) {
                            return "";
                        },
                        "target": "$['passwordNewInput:text']"
                    },
                    {
                        "source": "$",
                        "target_transformation": function(value, element) {
                            return "";
                        },
                        "target": "$['passwordConfirmInput:text']"
                    },
                    {
                        "source": "$",
                        "target_transformation": function(value, element) {
                            return "";
                        },
                        "target": "$['passwordCurrentInput:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["operationsRestaurantPage_createVendorProfile_vendor_create_service_onbeforesend_mapping_0"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": [
            {
                "from_name": "operationsRestaurantPage",
                "from_type": "UI",
                "to_name": "createVendorProfile_vendor_create_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": {
                        "state": {
                            "collName": "state"
                        },
                        "acl": {
                            "*": {
                                "write": true,
                                "read": true
                            }
                        }
                    }
                },
                "mappings": [
                    {
                        "source": "$['selectBusinessTypeButton:selectedMenuItem']",
                        "target": "$['body']['businessType']"
                    },
                    {
                        "source": "$['businessName:text']",
                        "target": "$['body']['businessName']"
                    },
                    {
                        "source": "$['streetAddress1:text']",
                        "target": "$['body']['streetAddress1']"
                    },
                    {
                        "source": "$['streetAddress2:text']",
                        "target": "$['body']['streetAddress2']"
                    },
                    {
                        "source": "$['city:text']",
                        "target": "$['body']['city']"
                    },
                    {
                        "source": "$['zip:text']",
                        "target": "$['body']['zip']"
                    },
                    {
                        "source": "$['phone:text']",
                        "target": "$['body']['phone']"
                    },
                    {
                        "source": "$['website:text']",
                        "target": "$['body']['website']"
                    },
                    {
                        "source": "$['contactName:text']",
                        "target": "$['body']['contactName']"
                    },
                    {
                        "source": "$['contactEmail:text']",
                        "target": "$['body']['contactEmail']"
                    },
                    {
                        "source": "$['chefHead:text']",
                        "target": "$['body']['chefHead']"
                    },
                    {
                        "source": "$['vendorDescription:text']",
                        "target": "$['body']['vendorDescription']"
                    },
                    {
                        "source": "$['mondayOpen:text']",
                        "target": "$['body']['mondayOpen']"
                    },
                    {
                        "source": "$['tuesdayOpen:text']",
                        "target": "$['body']['tuesdayOpen']"
                    },
                    {
                        "source": "$['wednesdayOpen:text']",
                        "target": "$['body']['wednesdayOpen']"
                    },
                    {
                        "source": "$['thursdayLabel:text']",
                        "target": "$['body']['thursdayOpen']"
                    },
                    {
                        "source": "$['saturdayOpen:text']",
                        "target": "$['body']['saturdayOpen']"
                    },
                    {
                        "source": "$['fridayOpen:text']",
                        "target": "$['body']['fridayOpen']"
                    },
                    {
                        "source": "$['sundayOpen:text']",
                        "target": "$['body']['sundayOpen']"
                    },
                    {
                        "source": "$['mondayClose:text']",
                        "target": "$['body']['mondayClose']"
                    },
                    {
                        "source": "$['tuesdayClose:text']",
                        "target": "$['body']['tuesdayClose']"
                    },
                    {
                        "source": "$['wednesdayClose:text']",
                        "target": "$['body']['wednesdayClose']"
                    },
                    {
                        "source": "$['thursdayClose:text']",
                        "target": "$['body']['thursdayClose']"
                    },
                    {
                        "source": "$['fridayClose:text']",
                        "target": "$['body']['fridayClose']"
                    },
                    {
                        "source": "$['saturdayClose:text']",
                        "target": "$['body']['saturdayClose']"
                    },
                    {
                        "source": "$['sundayClose:text']",
                        "target": "$['body']['sundayClose']"
                    },
                    {
                        "source": "$['contactPhone:text']",
                        "target": "$['body']['contactPhone']"
                    },
                    {
                        "source": "$['taxField:text']",
                        "target_transformation": function(value) {
                            return value ? (value / 100) : 0;
                        },
                        "target": "$['body']['taxRate']"
                    },
                    {
                        "source": "$['stateDropdown:selectedMenuItem']",
                        "target": "$['body']['state']['_id']"
                    }
                ]
            },
            {
                "from_name": "fileInfo",
                "from_type": "SESSION_STORAGE",
                "to_name": "createVendorProfile_vendor_create_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": {
                        "state": {
                            "collName": "state"
                        },
                        "acl": {
                            "*": {
                                "write": true,
                                "read": true
                            }
                        }
                    }
                },
                "mappings": [
                    {
                        "source": "$['fileName']",
                        "target": "$['body']['vendorImage']['fileName']"
                    },
                    {
                        "source": "$['originalFileName']",
                        "target": "$['body']['vendorImage']['originalFileName']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["operationsRestaurantPage_createVendorProfile_vendor_create_service_onsuccess_mapping_0"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": [
            {
                "from_name": "createVendorProfile_vendor_create_service",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "vendorId",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['_id']",
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "createVendorProfile_vendor_create_service",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "currentVendor",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['_id']",
                        "target": "$['id']"
                    }
                ]
            },
            {
                "from_name": "operationsRestaurantPage",
                "from_type": "UI",
                "to_name": "currentVendor",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['businessName:text']",
                        "target": "$['businessName']"
                    },
                    {
                        "source": "$['selectBusinessTypeButton:selectedMenuItem']",
                        "target": "$['businessType']"
                    },
                    {
                        "source": "$['vendorDescription:text']",
                        "target": "$['vendorDescription']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["operationsRestaurantPage_createVendorProfile_user_update_service_onbeforesend_mapping_0"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": [
            {
                "from_name": "userId",
                "from_type": "LOCAL_STORAGE",
                "to_name": "createVendorProfile_user_update_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}"
                    },
                    "parameters": {},
                    "body": {
                        "vendor_lk": {
                            "collName": "vendor"
                        }
                    }
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['userId']"
                    }
                ]
            },
            {
                "from_name": "vendorId",
                "from_type": "SESSION_STORAGE",
                "to_name": "createVendorProfile_user_update_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}"
                    },
                    "parameters": {},
                    "body": {
                        "vendor_lk": {
                            "collName": "vendor"
                        }
                    }
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['body']['vendor_lk']['_id']"
                    }
                ]
            },
            {
                "from_name": "userName",
                "from_type": "SESSION_STORAGE",
                "to_name": "createVendorProfile_user_update_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}"
                    },
                    "parameters": {},
                    "body": {
                        "vendor_lk": {
                            "collName": "vendor"
                        }
                    }
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['body']['username']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["operationsRestaurantPage_createVendorProfile_vendor_read_service_onsuccess_mapping_0"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": [
            {
                "from_name": "createVendorProfile_vendor_read_service",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "operationsRestaurantPage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['body']['businessName']",
                        "target": "$['businessName:text']"
                    },
                    {
                        "source": "$['body']['streetAddress1']",
                        "target": "$['streetAddress1:text']"
                    },
                    {
                        "source": "$['body']['streetAddress2']",
                        "target": "$['streetAddress2:text']"
                    },
                    {
                        "source": "$['body']['city']",
                        "target": "$['city:text']"
                    },
                    {
                        "source": "$['body']['phone']",
                        "target": "$['phone:text']"
                    },
                    {
                        "source": "$['body']['website']",
                        "target": "$['website:text']"
                    },
                    {
                        "source": "$['body']['contactName']",
                        "target": "$['contactName:text']"
                    },
                    {
                        "source": "$['body']['contactPhone']",
                        "target": "$['contactPhone:text']"
                    },
                    {
                        "source": "$['body']['contactEmail']",
                        "target": "$['contactEmail:text']"
                    },
                    {
                        "source": "$['body']['chefHead']",
                        "target": "$['chefHead:text']"
                    },
                    {
                        "source": "$['body']['vendorDescription']",
                        "target": "$['vendorDescription:text']"
                    },
                    {
                        "source": "$['body']['zip']",
                        "target": "$['zip:text']"
                    },
                    {
                        "source": "$['body']['state']['name']",
                        "target": "$['stateDropdown1:text']"
                    },
                    {
                        "source": "$['body']['businessType']",
                        "target": "$['selectBusinessTypeButton:selectedMenuItem']"
                    },
                    {
                        "source": "$['body']['taxRate']",
                        "target_transformation": function(value, element) {
                            return (value || 0) * 100;
                        },
                        "target": "$['taxField:text']"
                    },
                    {
                        "source": "$['body']['state']['_id']",
                        "target": "$['stateDropdown:selectedMenuItem']"
                    },
                    {
                        "source": "$['body']['vendorImage']['fileName']",
                        "target_transformation": function(value, element) {
                            if (value) {
                                return "https://api.appery.io/rest/1/db/files/" + Settings.database_id + "/" + value;
                            } else {
                                return NO_IMAGE_URL;
                            }
                        },
                        "target": "$['placeholderForImageUpload:image']"
                    },
                    {
                        "source": "$['body']['vendorImage']['fileName']",
                        "target_transformation": function(value, element) {
                            return value ? true : false;
                        },
                        "target": "$['placeholderForImageUpload:visible']"
                    },
                    {
                        "source": "$['body']['mondayOpen']",
                        "target": "$['mondayOpen:text']"
                    },
                    {
                        "source": "$['body']['tuesdayOpen']",
                        "target": "$['tuesdayOpen:text']"
                    },
                    {
                        "source": "$['body']['wednesdayOpen']",
                        "target": "$['wednesdayOpen:text']"
                    },
                    {
                        "source": "$['body']['thursdayOpen']",
                        "target": "$['thursdayOpen:text']"
                    },
                    {
                        "source": "$['body']['fridayOpen']",
                        "target": "$['fridayOpen:text']"
                    },
                    {
                        "source": "$['body']['saturdayOpen']",
                        "target": "$['saturdayOpen:text']"
                    },
                    {
                        "source": "$['body']['sundayOpen']",
                        "target": "$['sundayOpen:text']"
                    },
                    {
                        "source": "$['body']['mondayClose']",
                        "target": "$['mondayClose:text']"
                    },
                    {
                        "source": "$['body']['tuesdayClose']",
                        "target": "$['tuesdayClose:text']"
                    },
                    {
                        "source": "$['body']['wednesdayClose']",
                        "target": "$['wednesdayClose:text']"
                    },
                    {
                        "source": "$['body']['thursdayClose']",
                        "target": "$['thursdayClose:text']"
                    },
                    {
                        "source": "$['body']['fridayClose']",
                        "target": "$['fridayClose:text']"
                    },
                    {
                        "source": "$['body']['saturdayClose']",
                        "target": "$['saturdayClose:text']"
                    },
                    {
                        "source": "$['body']['sundayClose']",
                        "target": "$['sundayClose:text']"
                    }
                ]
            },
            {
                "from_name": "createVendorProfile_vendor_read_service",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "fileInfo",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['vendorImage']",
                        "target": "$"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["operationsRestaurantPage_createVendorProfile_vendor_read_service_onbeforesend_mapping_0"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": [
            {
                "from_name": "vendorId",
                "from_type": "SESSION_STORAGE",
                "to_name": "createVendorProfile_vendor_read_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}"
                    },
                    "parameters": {
                        "include": "state,country"
                    },
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['_id']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["operationsRestaurantPage_createVendorProfile_menuHeading_create_service_onsuccess_mapping_0"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": []
    };
    Apperyio.mappings["operationsRestaurantPage_createVendorProfile_menuHeading_create_service_onbeforesend_mapping_0"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": [
            {
                "from_name": "vendorId",
                "from_type": "SESSION_STORAGE",
                "to_name": "createVendorProfile_menuHeading_create_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": {
                        "vendor": {
                            "collName": "vendor"
                        },
                        "heading": "Menu",
                        "headingParent": {
                            "collName": "menuHeading"
                        },
                        "acl": {
                            "*": {
                                "write": true,
                                "read": true
                            }
                        },
                        "vend": {
                            "collName": "_users",
                            "_id": "{user_id}"
                        }
                    }
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['body']['vendor']['_id']"
                    }
                ]
            },
            {
                "to_name": "createVendorProfile_menuHeading_create_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": {
                        "vendor": {
                            "collName": "vendor"
                        },
                        "heading": "Menu",
                        "headingParent": {
                            "collName": "menuHeading"
                        },
                        "acl": {
                            "*": {
                                "write": true,
                                "read": true
                            }
                        },
                        "vend": {
                            "collName": "_users",
                            "_id": "{user_id}"
                        }
                    }
                },
                "mappings": [
                    {
                        "target_transformation": function(value) {
                            return null;
                        },
                        "target": "$['body']['headingParent']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["operationsRestaurantPage_createVendorProfile_vendor_update_service_onbeforesend_mapping_0"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": [
            {
                "from_name": "vendorId",
                "from_type": "SESSION_STORAGE",
                "to_name": "createVendorProfile_vendor_update_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": {
                        "acl": {
                            "*": {
                                "write": true,
                                "read": true
                            }
                        }
                    }
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['_id']"
                    }
                ]
            },
            {
                "from_name": "operationsRestaurantPage",
                "from_type": "UI",
                "to_name": "createVendorProfile_vendor_update_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": {
                        "acl": {
                            "*": {
                                "write": true,
                                "read": true
                            }
                        }
                    }
                },
                "mappings": [
                    {
                        "source": "$['contactName:text']",
                        "target": "$['body']['contactName']"
                    },
                    {
                        "source": "$['contactPhone:text']",
                        "target": "$['body']['contactPhone']"
                    },
                    {
                        "source": "$['contactEmail:text']",
                        "target": "$['body']['contactEmail']"
                    },
                    {
                        "source": "$['chefHead:text']",
                        "target": "$['body']['chefHead']"
                    },
                    {
                        "source": "$['streetAddress1:text']",
                        "target": "$['body']['streetAddress1']"
                    },
                    {
                        "source": "$['streetAddress2:text']",
                        "target": "$['body']['streetAddress2']"
                    },
                    {
                        "source": "$['city:text']",
                        "target": "$['body']['city']"
                    },
                    {
                        "source": "$['zip:text']",
                        "target": "$['body']['zip']"
                    },
                    {
                        "source": "$['businessName:text']",
                        "target": "$['body']['businessName']"
                    },
                    {
                        "source": "$['phone:text']",
                        "target": "$['body']['phone']"
                    },
                    {
                        "source": "$['website:text']",
                        "target": "$['body']['website']"
                    },
                    {
                        "source": "$['vendorDescription:text']",
                        "target": "$['body']['vendorDescription']"
                    },
                    {
                        "source": "$['selectBusinessTypeButton:selectedMenuItem']",
                        "target": "$['body']['businessType']"
                    },
                    {
                        "source": "$['taxField:text']",
                        "target_transformation": function(value) {
                            return value ? (value / 100) : 0;
                        },
                        "target": "$['body']['taxRate']"
                    },
                    {
                        "source": "$['stateDropdown:selectedMenuItem']",
                        "target_transformation": function(value) {
                            if (value) {
                                return {
                                    collName: "state",
                                    _id: value
                                };
                            } else {
                                return null;
                            }
                        },
                        "target": "$['body']['state']"
                    },
                    {
                        "source": "$['mondayOpen:text']",
                        "target": "$['body']['mondayOpen']"
                    },
                    {
                        "source": "$['wednesdayOpen:text']",
                        "target": "$['body']['wednesdayOpen']"
                    },
                    {
                        "source": "$['tuesdayOpen:text']",
                        "target": "$['body']['tuesdayOpen']"
                    },
                    {
                        "source": "$['thursdayOpen:text']",
                        "target": "$['body']['thursdayOpen']"
                    },
                    {
                        "source": "$['fridayOpen:text']",
                        "target": "$['body']['fridayOpen']"
                    },
                    {
                        "source": "$['saturdayOpen:text']",
                        "target": "$['body']['saturdayOpen']"
                    },
                    {
                        "source": "$['tuesdayClose:text']",
                        "target": "$['body']['tuesdayClose']"
                    },
                    {
                        "source": "$['mondayClose:text']",
                        "target": "$['body']['mondayClose']"
                    },
                    {
                        "source": "$['sundayClose:text']",
                        "target": "$['body']['sundayClose']"
                    },
                    {
                        "source": "$['saturdayClose:text']",
                        "target": "$['body']['saturdayClose']"
                    },
                    {
                        "source": "$['fridayClose:text']",
                        "target": "$['body']['fridayClose']"
                    },
                    {
                        "source": "$['thursdayClose:text']",
                        "target": "$['body']['thursdayClose']"
                    },
                    {
                        "source": "$['wednesdayClose:text']",
                        "target": "$['body']['wednesdayClose']"
                    },
                    {
                        "source": "$['sundayOpen:text']",
                        "target": "$['body']['sundayOpen']"
                    }
                ]
            },
            {
                "from_name": "fileInfo",
                "from_type": "SESSION_STORAGE",
                "to_name": "createVendorProfile_vendor_update_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": {
                        "acl": {
                            "*": {
                                "write": true,
                                "read": true
                            }
                        }
                    }
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['body']['vendorImage']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["operationsRestaurantPage_createVendorProfile_vendor_update_service_onsuccess_mapping_1"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": [
            {
                "from_name": "operationsRestaurantPage",
                "from_type": "UI",
                "to_name": "currentVendor",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['businessName:text']",
                        "target": "$['businessName']"
                    },
                    {
                        "source": "$['vendorDescription:text']",
                        "target": "$['vendorDescription']"
                    },
                    {
                        "source": "$['selectBusinessTypeButton:selectedMenuItem']",
                        "target": "$['businessType']"
                    },
                    {
                        "source": "$['taxField:text']",
                        "target_transformation": function(value) {
                            return value ? (value / 10) : 0;
                        },
                        "target": "$['taxRate']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["operationsRestaurantPage_vendorProfile_resetPassword_service_onbeforesend_mapping_0"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": [
            {
                "from_name": "userName",
                "from_type": "SESSION_STORAGE",
                "to_name": "vendorProfile_resetPassword_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "Content-Type": "text/plain"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['username']"
                    }
                ]
            },
            {
                "from_name": "operationsRestaurantPage",
                "from_type": "UI",
                "to_name": "vendorProfile_resetPassword_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "Content-Type": "text/plain"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$['passwordCurrentInput:text']",
                        "target": "$['parameters']['oldPassword']"
                    },
                    {
                        "source": "$['passwordNewInput:text']",
                        "target": "$['parameters']['newPassword']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["operationsRestaurantPage_vendorProfile_user_query_service_onbeforesend_mapping_0"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": [
            {
                "to_name": "vendorProfile_user_query_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}"
                    },
                    "parameters": {
                        "where": "{\"userType\": \"customer\"}",
                        "limit": "2000"
                    },
                    "body": null
                },
                "mappings": []
            }
        ]
    };
    Apperyio.mappings["operationsRestaurantPage_vendorProfile_user_updateEmail_service_onbeforesend_mapping_0"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": [
            {
                "from_name": "userId",
                "from_type": "LOCAL_STORAGE",
                "to_name": "vendorProfile_user_updateEmail_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}"
                    },
                    "parameters": {},
                    "body": {
                        "vendor_lk": {
                            "collName": "vendor"
                        }
                    }
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['userId']"
                    }
                ]
            },
            {
                "from_name": "operationsRestaurantPage",
                "from_type": "UI",
                "to_name": "vendorProfile_user_updateEmail_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}"
                    },
                    "parameters": {},
                    "body": {
                        "vendor_lk": {
                            "collName": "vendor"
                        }
                    }
                },
                "mappings": [
                    {
                        "source": "$['emailField:text']",
                        "target": "$['body']['username']"
                    }
                ]
            },
            {
                "from_name": "vendorId",
                "from_type": "SESSION_STORAGE",
                "to_name": "vendorProfile_user_updateEmail_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}"
                    },
                    "parameters": {},
                    "body": {
                        "vendor_lk": {
                            "collName": "vendor"
                        }
                    }
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['body']['vendor_lk']['_id']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["operationsRestaurantPage_vendorProfile_user_updateEmail_service_onsuccess_mapping_0"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": [
            {
                "from_name": "operationsRestaurantPage",
                "from_type": "UI",
                "to_name": "userName",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['emailField:text']",
                        "target": "$"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["operationsRestaurantPage_vendorProfile_state_list_service_onbeforesend_mapping_0"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": [
            {
                "to_name": "vendorProfile_state_list_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}"
                    },
                    "parameters": {
                        "order": "+name"
                    },
                    "body": null
                },
                "mappings": []
            }
        ]
    };
    Apperyio.mappings["operationsRestaurantPage_vendorProfile_state_list_service_onsuccess_mapping_0"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": [
            {
                "from_name": "vendorProfile_state_list_service",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "operationsRestaurantPage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['body'][i]",
                        "target": "$['stateDropdown-0']"
                    },
                    {
                        "source": "$['body'][i]['_id']",
                        "target": "$['stateDropdown-0:value']"
                    },
                    {
                        "source": "$['body'][i]['abbreviation']",
                        "target": "$['stateDropdown-0:label']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["operationsRestaurantPage_vendorProfile_files_delete_service_onbeforesend_mapping_0"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": [
            {
                "from_name": "fileInfo",
                "from_type": "SESSION_STORAGE",
                "to_name": "vendorProfile_files_delete_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}",
                        "X-Appery-Master-Key": "{database_master_key}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$['fileName']",
                        "target": "$['parameters']['file_name']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["operationsRestaurantPage_vendorProfile_files_upload_service_onbeforesend_mapping_0"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": [
            {
                "to_name": "vendorProfile_files_upload_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}",
                        "X-Appery-Master-Key": "{database_master_key}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": []
            }
        ]
    };
    Apperyio.mappings["operationsRestaurantPage_vendorProfile_files_upload_service_onsuccess_mapping_0"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": []
    };
    Apperyio.mappings["operationsRestaurantPage_vendorProfile_gallery_service_onbeforesend_mapping_0"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": [
            {
                "to_name": "vendorProfile_gallery_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "quality": 80,
                        "destinationType": "Data URL",
                        "sourceType": "Photolibrary",
                        "allowEdit": true,
                        "encodingType": "JPEG",
                        "targetWidth": 1024,
                        "targetHeight": 768
                    }
                },
                "mappings": []
            }
        ]
    };
    Apperyio.mappings["operationsRestaurantPage_vendorProfile_gallery_service_onsuccess_mapping_0"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": [
            {
                "from_name": "vendorProfile_gallery_service",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "imageDataBase64",
                "to_type": "VARIABLE_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['imageDataBase64']",
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "vendorProfile_gallery_service",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "imageURI",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['imageURI']",
                        "target": "$"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["operationsRestaurantPage_vendorProfile_fileUpload_service_onbeforesend_mapping_0"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": [
            {
                "from_name": "imageURI",
                "from_type": "SESSION_STORAGE",
                "to_name": "vendorProfile_fileUpload_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "request_options": {
                            "headers": {
                                "Connection": "Close"
                            }
                        }
                    }
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['data']['image_uri']"
                    }
                ]
            },
            {
                "to_name": "vendorProfile_fileUpload_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "request_options": {
                            "headers": {
                                "Connection": "Close"
                            }
                        }
                    }
                },
                "mappings": [
                    {
                        "target_transformation": function(value) {
                            return projectMdb1_settings.database_master_key;
                        },
                        "target": "$['data']['request_options']['headers']['X-Appery-Master-Key']"
                    },
                    {
                        "target_transformation": function(value) {
                            return projectMdb1_settings.database_id;
                        },
                        "target": "$['data']['request_options']['headers']['X-Appery-Database-Id']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["operationsRestaurantPage_vendorProfile_updateVendorCoords_service_onsuccess_mapping_0"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": []
    };
    Apperyio.mappings["operationsRestaurantPage_vendorProfile_updateVendorCoords_service_onbeforesend_mapping_0"] = {
        "homeScreen": "operationsRestaurantPage",
        "directions": [
            {
                "from_name": "vendorId",
                "from_type": "SESSION_STORAGE",
                "to_name": "vendorProfile_updateVendorCoords_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Session-Token": "4a58e4f9-1295-4245-8726-b2478c624701",
                        "Content-Type": "text/plain"
                    },
                    "parameters": {
                        "vendor": "5714a09ce4b06624d2ed6c8f"
                    },
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['vendor']"
                    }
                ]
            },
            {
                "from_name": "sessionToken",
                "from_type": "SESSION_STORAGE",
                "to_name": "vendorProfile_updateVendorCoords_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Session-Token": "4a58e4f9-1295-4245-8726-b2478c624701",
                        "Content-Type": "text/plain"
                    },
                    "parameters": {
                        "vendor": "5714a09ce4b06624d2ed6c8f"
                    },
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['headers']['X-Appery-Session-Token']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.createVendorProfile_vendor_create_service = Apperyio.datasources.createVendorProfile_vendor_create_service = new Apperyio.DataSource(projectMdb1_vendor_create_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_createVendorProfile_vendor_create_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_createVendorProfile_vendor_create_service_onsuccess_mapping_0"]);
            projectMdb1_settings.vendor_id = storageGet('vendorId');
            try {
                createVendorProfile_user_update_service.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
            try {
                vendorProfile_updateVendorCoords_service.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.createVendorProfile_user_update_service = Apperyio.datasources.createVendorProfile_user_update_service = new Apperyio.DataSource(projectMdb1_user_update_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_createVendorProfile_user_update_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            try {
                createVendorProfile_menuHeading_create_service.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.createVendorProfile_vendor_read_service = Apperyio.datasources.createVendorProfile_vendor_read_service = new Apperyio.DataSource(projectMdb1_vendor_read_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_createVendorProfile_vendor_read_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_createVendorProfile_vendor_read_service_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.createVendorProfile_menuHeading_create_service = Apperyio.datasources.createVendorProfile_menuHeading_create_service = new Apperyio.DataSource(projectMdb1_menuHeading_create_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_createVendorProfile_menuHeading_create_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_createVendorProfile_menuHeading_create_service_onsuccess_mapping_0"]);
            Apperyio.navigateTo('proprietorStartPage', {
                reverse: false
            });
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.createVendorProfile_vendor_update_service = Apperyio.datasources.createVendorProfile_vendor_update_service = new Apperyio.DataSource(projectMdb1_vendor_update_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_createVendorProfile_vendor_update_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.navigateTo('proprietorStartPage', {
                reverse: false
            });
            Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_createVendorProfile_vendor_update_service_onsuccess_mapping_1"]);
            try {
                vendorProfile_updateVendorCoords_service.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.vendorProfile_resetPassword_service = Apperyio.datasources.vendorProfile_resetPassword_service = new Apperyio.DataSource(resetPassword_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_vendorProfile_resetPassword_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            var messageLabel = Apperyio('errorMessageLabel');
            if (data.status != 200) {
                if (data.body.code === 'DBUI112') {
                    messageLabel.text('The current password you\'ve entered is incorrect.');
                } else {
                    messageLabel.text(data.body.description);
                }
                messageLabel.show();
            } else {
                messageLabel.hide();
                setTimeout(function() {
                    showPopupWithTimout('messagePopup', 2500);
                }, 150);
                Apperyio('passwordChangePopup').popup('close');
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.vendorProfile_user_query_service = Apperyio.datasources.vendorProfile_user_query_service = new Apperyio.DataSource(projectMdb1_customers_list_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_vendorProfile_user_query_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {},
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.vendorProfile_user_updateEmail_service = Apperyio.datasources.vendorProfile_user_updateEmail_service = new Apperyio.DataSource(projectMdb1_user_update_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_vendorProfile_user_updateEmail_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
            Apperyio('loginChangePopup').popup('close');
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_vendorProfile_user_updateEmail_service_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.vendorProfile_state_list_service = Apperyio.datasources.vendorProfile_state_list_service = new Apperyio.DataSource(projectMdb1_state_list_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_vendorProfile_state_list_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_vendorProfile_state_list_service_onsuccess_mapping_0"]);
            if (storageGet('vendorId')) {
                createVendorProfile_vendor_read_service.execute({});
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.vendorProfile_files_delete_service = Apperyio.datasources.vendorProfile_files_delete_service = new Apperyio.DataSource(projectMdb1__files_delete_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_vendorProfile_files_delete_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {},
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.vendorProfile_files_upload_service = Apperyio.datasources.vendorProfile_files_upload_service = new Apperyio.DataSource(projectMdb1__files_upload_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_vendorProfile_files_upload_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_vendorProfile_files_upload_service_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.vendorProfile_gallery_service = Apperyio.datasources.vendorProfile_gallery_service = new Apperyio.DataSource(CameraService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_vendorProfile_gallery_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_vendorProfile_gallery_service_onsuccess_mapping_0"]);
            // show image preview
            var imageURI = storageGet('imageDataBase64');
            var previewContainer = Apperyio('placeholderForImageUpload');
            previewContainer.attr('src', imageURI);
            Apperyio('placeholderForImageUpload').show();
            imageHasBeenChanged = true;
            storageSet('fileInfo', {
                fileName: null,
                originalFileName: null
            });;
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.vendorProfile_fileUpload_service = Apperyio.datasources.vendorProfile_fileUpload_service = new Apperyio.DataSource(FileUpload_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_vendorProfile_fileUpload_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
            var service = projectMdb1_settings.vendor_id ? createVendorProfile_vendor_update_service : createVendorProfile_vendor_create_service,
                imgData = storageGet('imageDataBase64');
            if (imgData) {
                uploadBinaryHelper(vendorProfile_files_upload_service, storageGet('imageDataBase64'), null, null, service);
            } else {
                storageSet('fileInfo', {
                    fileName: null,
                    originalFileName: null
                });
                service.execute({});
            };
        },
        "onSuccess": function(data) {},
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.vendorProfile_updateVendorCoords_service = Apperyio.datasources.vendorProfile_updateVendorCoords_service = new Apperyio.DataSource(updateVendorCoords_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_vendorProfile_updateVendorCoords_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_vendorProfile_updateVendorCoords_service_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'operationsRestaurantPage';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var operationsRestaurantPage_onLoad = function() {
        operationsRestaurantPage_elementsExtraJS();
        imageHasBeenChanged = false;
        _.each(['businessName', 'streetAddress1', 'streetAddress2', 'city',
            'stateDropdown1', 'zip', 'phone', 'website', 'contactName',
            'contactPhone', 'contactEmail', 'chefHead', 'vendorDescription'
        ], function(value) {
            var element = Apperyio(value);
            if (element) {
                element.text('');
            }
        });
        vendorProfile_state_list_service.execute({});
        operationsRestaurantPage_deviceEvents();
        operationsRestaurantPage_windowEvents();
        operationsRestaurantPage_elementsEvents();
    };
    // screen window events
    function operationsRestaurantPage_windowEvents() {
        $('#operationsRestaurantPage').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function operationsRestaurantPage_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function operationsRestaurantPage_elementsExtraJS() {
        // screen (operationsRestaurantPage) extra code
        /* selectBusinessTypeButton */
        $("#operationsRestaurantPage_selectBusinessTypeButton").parent().find("a.ui-btn").attr("tabindex", "1");
        /* stateDropdown */
        $("#operationsRestaurantPage_stateDropdown").parent().find("a.ui-btn").attr("tabindex", "79");
        /* passwordChangePopup */
        $("#operationsRestaurantPage_passwordChangePopup").popup("option", "positionTo", "window");
        /* messagePopup */
        $("#operationsRestaurantPage_messagePopup").popup("option", "positionTo", "window");
        /* loginChangePopup */
        $("#operationsRestaurantPage_loginChangePopup").popup("option", "positionTo", "window");
        /* deactivateAccountPopup */
        $("#operationsRestaurantPage_deactivateAccountPopup").popup("option", "positionTo", "window");
        /* photoDeletePopup */
        $("#operationsRestaurantPage_photoDeletePopup").popup("option", "positionTo", "window");
    };
    // screen elements handler
    function operationsRestaurantPage_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#operationsRestaurantPage_operationsHeader [name="homeButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('proprietorStartPage', {
                        transition: 'slidedown',
                        reverse: false
                    });
                }
            },
        }, '#operationsRestaurantPage_operationsHeader [name="homeButton"]');
        $(document).off("click", '#operationsRestaurantPage_operationsContainer [name="loginChangeButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_loginChangeButton_onclick_mapping_0"]);
                    Apperyio('vaildEmailMessage').hide();
                    log(Apperyio('vaildEmailMessage'));
                    Apperyio('invalidEmailMessage').hide();
                    log(Apperyio('invalidEmailMessage'));
                    var popupElement = Apperyio("loginChangePopup");
                    if (popupElement.popup("option", "positionTo") === "origin") {
                        popupElement.popup("open", {
                            transition: "none",
                            positionTo: "#" + $(this).attr("id")
                        });
                    } else {
                        popupElement.popup("open", {
                            transition: "none"
                        });
                    };
                }
            },
        }, '#operationsRestaurantPage_operationsContainer [name="loginChangeButton"]');
        $(document).off("click", '#operationsRestaurantPage_operationsContainer [name="passwordChangeButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.processMappingAction(Apperyio.mappings["operationsRestaurantPage_passwordChangeButton_onclick_mapping_0"]);
                    var popupElement = Apperyio("passwordChangePopup");
                    if (popupElement.popup("option", "positionTo") === "origin") {
                        popupElement.popup("open", {
                            transition: "pop",
                            positionTo: "#" + $(this).attr("id")
                        });
                    } else {
                        popupElement.popup("open", {
                            transition: "pop"
                        });
                    };
                }
            },
        }, '#operationsRestaurantPage_operationsContainer [name="passwordChangeButton"]');
        $(document).off("click", '#operationsRestaurantPage_operationsContainer [name="copyMenuLinkButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var vendorId = storageGet('vendorId')
                    $.copyToClipboard('https://knowye.app.appery.io/app/menu_shared.html?vendor=' + vendorId);
                    var btnTitle = Apperyio('copyMenuLinkButton').html();
                    Apperyio('copyMenuLinkButton').html('Copied to Clipboard');
                    setTimeout(function() {
                        Apperyio('copyMenuLinkButton').html(btnTitle);
                    }, 1000);
                }
            },
        }, '#operationsRestaurantPage_operationsContainer [name="copyMenuLinkButton"]');
        $(document).off("input", '#operationsRestaurantPage_operationsContainer [name="taxField"]').on({
            input: function(event) {
                var element = $(this);
                if (!$.isNumeric(element.val())) {
                    element.val(0);
                } else {
                    if (element.val() > 25) {
                        element.val(25);
                    } else if (element.val() < 0) {
                        element.val(0);
                    }
                };
            },
        }, '#operationsRestaurantPage_operationsContainer [name="taxField"]');
        $(document).off("change", '#operationsRestaurantPage_operationsContainer [name="fileSelect"]').on({
            change: function(event) {
                /* Image was loaded into memory using `fileUpload` field in browser 
                   `previewFile()` sets variable `imageDataBase64` with image data.
                   `fileInfo` variable that consists of `fileName` and `originalFileName` fields
                   is reset to `null` filenames.
                 */
                imageHasBeenChanged = true;
                var callback = function(event) {
                    var previewContainer = Apperyio('placeholderForImageUpload');
                    previewContainer.attr('src', event.target.result);
                    Apperyio('placeholderForImageUpload').show();
                    console.log('Image loaded as base64');
                };
                previewFile(event, callback);
            },
        }, '#operationsRestaurantPage_operationsContainer [name="fileSelect"]');
        $(document).off("click", '#operationsRestaurantPage_operationsContainer [name="addImageButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    /* Upload image to Files collection and send it to the preview field. */
                    if (window.cordova) {
                        vendorProfile_gallery_service.execute({});
                    } else {
                        Apperyio('fileSelect').click();
                    }
                    return false;
                }
            },
        }, '#operationsRestaurantPage_operationsContainer [name="addImageButton"]');
        $(document).off("click", '#operationsRestaurantPage_operationsContainer [name="deleteImageButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var popupElement = Apperyio("photoDeletePopup");
                    if (popupElement.popup("option", "positionTo") === "origin") {
                        popupElement.popup("open", {
                            transition: "none",
                            positionTo: "#" + $(this).attr("id")
                        });
                    } else {
                        popupElement.popup("open", {
                            transition: "none"
                        });
                    };
                }
            },
        }, '#operationsRestaurantPage_operationsContainer [name="deleteImageButton"]');
        $(document).off("click", '#operationsRestaurantPage_operationsContainer [name="operationsInfoSave"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    operationsRestaurantPage_saveButton();
                }
            },
        }, '#operationsRestaurantPage_operationsContainer [name="operationsInfoSave"]');
        $(document).off("click", '#operationsRestaurantPage_operationsContainer [name="operationInfoCancelButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('proprietorStartPage', {
                        transition: 'slide',
                        reverse: true
                    });
                }
            },
        }, '#operationsRestaurantPage_operationsContainer [name="operationInfoCancelButton"]');
        $(document).off("click", '#operationsRestaurantPage_operationsContainer [name="deactivateAccountLink"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var popupElement = Apperyio("deactivateAccountPopup");
                    if (popupElement.popup("option", "positionTo") === "origin") {
                        popupElement.popup("open", {
                            transition: "slideup",
                            positionTo: "#" + $(this).attr("id")
                        });
                    } else {
                        popupElement.popup("open", {
                            transition: "slideup"
                        });
                    };
                }
            },
        }, '#operationsRestaurantPage_operationsContainer [name="deactivateAccountLink"]');
        $(document).off("input", '#operationsRestaurantPage_passwordChangePopup [name="passwordCurrentInput"]').on({
            input: function(event) {
                Apperyio('errorMessageLabel').hide();
            },
        }, '#operationsRestaurantPage_passwordChangePopup [name="passwordCurrentInput"]');
        $(document).off("input", '#operationsRestaurantPage_passwordChangePopup [name="passwordNewInput"]').on({
            input: function(event) {
                passwardMatchingValidate('passwordNewInput', 'passwordConfirmInput', 'errorMessageLabel');
            },
        }, '#operationsRestaurantPage_passwordChangePopup [name="passwordNewInput"]');
        $(document).off("input", '#operationsRestaurantPage_passwordChangePopup [name="passwordConfirmInput"]').on({
            input: function(event) {
                passwardMatchingValidate('passwordNewInput', 'passwordConfirmInput', 'errorMessageLabel');
            },
        }, '#operationsRestaurantPage_passwordChangePopup [name="passwordConfirmInput"]');
        $(document).off("click", '#operationsRestaurantPage_passwordChangePopup [name="mobilebutton_23"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    if (passwardMatchingValidate('passwordNewInput', 'passwordConfirmInput', 'errorMessageLabel')) {
                        vendorProfile_resetPassword_service.execute({});
                    };
                }
            },
        }, '#operationsRestaurantPage_passwordChangePopup [name="mobilebutton_23"]');
        $(document).off("click", '#operationsRestaurantPage_passwordChangePopup [name="passwordCancelButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('deactivateAccountPopup').popup('close');
                }
            },
        }, '#operationsRestaurantPage_passwordChangePopup [name="passwordCancelButton"]');
        $(document).off("click", '#operationsRestaurantPage_loginChangePopup [name="loginSaveButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    if (verifyEmail(Apperyio('emailField').val(), Apperyio('invalidEmailMessage'))) {
                        vendorProfile_user_query_service.execute({
                            success: function(data) {
                                if (data.length) {
                                    var invalidMessage = Apperyio('invalidEmailMessage');
                                    invalidMessage.text('This email is already used! Try another one.');
                                    invalidMessage.show();
                                    Apperyio('validEmailMessage').hide();
                                } else {
                                    Apperyio('validEmailMessage').hide();
                                    Apperyio('invalidEmailMessage').hide();
                                    vendorProfile_user_updateEmail_service.execute({});
                                }
                            }
                        });
                    };
                }
            },
        }, '#operationsRestaurantPage_loginChangePopup [name="loginSaveButton"]');
        $(document).off("click", '#operationsRestaurantPage_loginChangePopup [name="changeloginCancelButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('deactivateAccountPopup').popup('close');
                }
            },
        }, '#operationsRestaurantPage_loginChangePopup [name="changeloginCancelButton"]');
        $(document).off("click", '#operationsRestaurantPage_deactivateAccountPopup [name="deactivateAccountCancelButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('deactivateAccountPopup').popup('close');
                }
            },
        }, '#operationsRestaurantPage_deactivateAccountPopup [name="deactivateAccountCancelButton"]');
        $(document).off("click", '#operationsRestaurantPage_photoDeletePopup [name="photoDeleteOkButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    imageHasBeenChanged = true;
                    var previewContainer = Apperyio('placeholderForImageUpload');
                    previewContainer.attr('src', NO_IMAGE_URL);
                    storageSet('imageDataBase64', '');
                    Apperyio('placeholderForImageUpload').hide();
                    Apperyio('photoDeletePopup').popup('close');
                }
            },
        }, '#operationsRestaurantPage_photoDeletePopup [name="photoDeleteOkButton"]');
        $(document).off("click", '#operationsRestaurantPage_photoDeletePopup [name="photoDeleteCancelButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('photoDeletePopup').popup('close');
                }
            },
        }, '#operationsRestaurantPage_photoDeletePopup [name="photoDeleteCancelButton"]');
    };
    $(document).off("pagebeforeshow", "#operationsRestaurantPage").on("pagebeforeshow", "#operationsRestaurantPage", function(event, ui) {
        Apperyio.CurrentScreen = "operationsRestaurantPage";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    operationsRestaurantPage_onLoad();
};
$(document).off("pagecreate", "#operationsRestaurantPage").on("pagecreate", "#operationsRestaurantPage", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    operationsRestaurantPage_js();
});