/*
 * JS for startScreen generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '148444cb-eb26-4cec-bc22-29bf794bc529';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
// Appery.io push registration service
var _pushRegistrationApperyService = new Apperyio.RestService({
    'url': 'https://api.appery.io/rest/push/reg',
    'dataType': 'json',
    'type': 'post',
    'contentType': 'application/json',
});
Apperyio.AppPages = [{
    "name": "aboutPage",
    "location": "aboutPage.html"
}, {
    "name": "itemDetailsPage",
    "location": "itemDetailsPage.html"
}, {
    "name": "menuHeadingManagePage",
    "location": "menuHeadingManagePage.html"
}, {
    "name": "proprietorAnalyticsPage",
    "location": "proprietorAnalyticsPage.html"
}, {
    "name": "zzpromoEdit",
    "location": "zzpromoEdit.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "itemPage",
    "location": "itemPage.html"
}, {
    "name": "zzpromoManage",
    "location": "zzpromoManage.html"
}, {
    "name": "zzscannerPage",
    "location": "zzscannerPage.html"
}, {
    "name": "zztimeRangePage",
    "location": "zztimeRangePage.html"
}, {
    "name": "selectedPage",
    "location": "selectedPage.html"
}, {
    "name": "zzCSStestPage",
    "location": "zzCSStestPage.html"
}, {
    "name": "zzmenuPage",
    "location": "zzmenuPage.html"
}, {
    "name": "menuHistoryPage",
    "location": "menuHistoryPage.html"
}, {
    "name": "faqPage",
    "location": "faqPage.html"
}, {
    "name": "zzratingInfoPage",
    "location": "zzratingInfoPage.html"
}, {
    "name": "orderHistoryPage",
    "location": "orderHistoryPage.html"
}, {
    "name": "createAccount",
    "location": "createAccount.html"
}, {
    "name": "itemManagePage",
    "location": "itemManagePage.html"
}, {
    "name": "proprietorStartPage",
    "location": "proprietorStartPage.html"
}, {
    "name": "operationsRestaurantPage",
    "location": "operationsRestaurantPage.html"
}, {
    "name": "zzdetailedReviewPage",
    "location": "zzdetailedReviewPage.html"
}, {
    "name": "itemEditPage",
    "location": "itemEditPage.html"
}, {
    "name": "selectionHistoryPage",
    "location": "selectionHistoryPage.html"
}, {
    "name": "zzproprietorStatPage",
    "location": "zzproprietorStatPage.html"
}, {
    "name": "zzitemInventoryPage",
    "location": "zzitemInventoryPage.html"
}, {
    "name": "zzalertPage",
    "location": "zzalertPage.html"
}, {
    "name": "zzsearchPage",
    "location": "zzsearchPage.html"
}, {
    "name": "menuPage_v2",
    "location": "menuPage_v2.html"
}, {
    "name": "zzqrCodePage",
    "location": "zzqrCodePage.html"
}, {
    "name": "profilePage",
    "location": "profilePage.html"
}, {
    "name": "filterPage",
    "location": "filterPage.html"
}, {
    "name": "easterEggPage",
    "location": "easterEggPage.html"
}, {
    "name": "helpPage",
    "location": "helpPage.html"
}, {
    "name": "navigatePage",
    "location": "navigatePage.html"
}, {
    "name": "menuPreviewPage",
    "location": "menuPreviewPage.html"
}, {
    "name": "zzfacebookLogin",
    "location": "zzfacebookLogin.html"
}, {
    "name": "menu_shared",
    "location": "menu_shared.html"
}, {
    "name": "logoutPage",
    "location": "logoutPage.html"
}, {
    "name": "favoritesPage",
    "location": "favoritesPage.html"
}, {
    "name": "proprietorPage",
    "location": "proprietorPage.html"
}, {
    "name": "wishListPage",
    "location": "wishListPage.html"
}, {
    "name": "menuManagementPage",
    "location": "menuManagementPage.html"
}, {
    "name": "touPage",
    "location": "touPage.html"
}, {
    "name": "zzsettingsPage",
    "location": "zzsettingsPage.html"
}];

function startScreen_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'helpButton': 'startScreen_helpButton',
        'knowyeLogo': 'startScreen_knowyeLogo',
        'scanMenuCodeButton': 'startScreen_scanMenuCodeButton',
        'gotoSearch': 'startScreen_gotoSearch',
        'loginForm': 'startScreen_loginForm',
        'loginCell': 'startScreen_loginCell',
        'loginField': 'startScreen_loginField',
        'passwordCell': 'startScreen_passwordCell',
        'passwordField': 'startScreen_passwordField',
        'errorLabel': 'startScreen_errorLabel',
        'loginButton': 'startScreen_loginButton',
        'forgotPwLabel': 'startScreen_forgotPwLabel',
        'amazonLogin': 'startScreen_amazonLogin',
        'facebookLogin': 'startScreen_facebookLogin',
        'createAccountButton': 'startScreen_createAccountButton',
        'touPrivacyGrid': 'startScreen_touPrivacyGrid',
        'touCell': 'startScreen_touCell',
        'touLabel': 'startScreen_touLabel',
        'privacyCell': 'startScreen_privacyCell',
        'privacyLabel': 'startScreen_privacyLabel',
        'introPopupLabel1': 'startScreen_introPopupLabel1',
        'introPopupLabel2': 'startScreen_introPopupLabel2',
        'showAgainChkBox': 'startScreen_showAgainChkBox',
        'showAgainCheck': 'startScreen_showAgainCheck',
        'introPopupContinueButton': 'startScreen_introPopupContinueButton',
        'createAccountPopupLabel': 'startScreen_createAccountPopupLabel',
        'accountTypeList': 'startScreen_accountTypeList',
        'personSelectButton': 'startScreen_personSelectButton',
        'mobilelistitembutton_43': 'startScreen_mobilelistitembutton_43',
        'proprietorSelectButton': 'startScreen_proprietorSelectButton',
        'mobilelistitembutton_45': 'startScreen_mobilelistitembutton_45',
        'resetPwButton': 'startScreen_resetPwButton',
        'resetPasswordTempLabel': 'startScreen_resetPasswordTempLabel',
        'resetPwAddressLink': 'startScreen_resetPwAddressLink',
        'forgotPasswordLabel': 'startScreen_forgotPasswordLabel',
        'emailInput': 'startScreen_emailInput',
        'forgotPasswordButton': 'startScreen_forgotPasswordButton',
        'locationPopupGrid': 'startScreen_locationPopupGrid',
        'mobilegridcell_48': 'startScreen_mobilegridcell_48',
        'locationsCloseBtn': 'startScreen_locationsCloseBtn',
        'mobilegridcell_49': 'startScreen_mobilegridcell_49',
        'locationsLabel': 'startScreen_locationsLabel',
        'featureLocationList': 'startScreen_featureLocationList',
        'featureLocationsItem': 'startScreen_featureLocationsItem',
        'mobilelistitembutton_67': 'startScreen_mobilelistitembutton_67',
        'locationList': 'startScreen_locationList',
        'locationsListItem': 'startScreen_locationsListItem',
        'mobilelistitembutton_55': 'startScreen_mobilelistitembutton_55',
        'rpw_close_btn': 'startScreen_rpw_close_btn',
        'rpw_title': 'startScreen_rpw_title',
        'rpw_instruction_label': 'startScreen_rpw_instruction_label',
        'rpw_email': 'startScreen_rpw_email',
        'rpw_error': 'startScreen_rpw_error',
        'rpw_send_code': 'startScreen_rpw_send_code',
        'resetpass_close_btn': 'startScreen_resetpass_close_btn',
        'resetpass_title': 'startScreen_resetpass_title',
        'resetpass_msg': 'startScreen_resetpass_msg',
        'resetpass_response_error': 'startScreen_resetpass_response_error',
        'resetpass_email': 'startScreen_resetpass_email',
        'resetpass_email_error': 'startScreen_resetpass_email_error',
        'resetpass_secret': 'startScreen_resetpass_secret',
        'resetpass_secret_error': 'startScreen_resetpass_secret_error',
        'resetpass_new_pass': 'startScreen_resetpass_new_pass',
        'resetpass_confirm_pass': 'startScreen_resetpass_confirm_pass',
        'resetpass_pass_error': 'startScreen_resetpass_pass_error',
        'resetpass_submit': 'startScreen_resetpass_submit'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["startScreen_loginService_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [
            {
                "from_name": "loginService",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "sessionToken",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['sessionToken']",
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "loginService",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "userId",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['_id']",
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "startScreen",
                "from_type": "UI",
                "to_name": "userName",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['loginField:text']",
                        "target": "$"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["startScreen_loginService_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [
            {
                "from_name": "startScreen",
                "from_type": "UI",
                "to_name": "loginService",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$['loginField:text']",
                        "target": "$['parameters']['username']"
                    },
                    {
                        "source": "$['passwordField:text']",
                        "target": "$['parameters']['password']"
                    }
                ]
            }
        ]
    };

    Apperyio.mappings["startScreen_usetTypeService_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [
            {
                "from_name": "usetTypeService",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "userType",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['userType']",
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "usetTypeService",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "userId",
                "to_type": "LOCAL_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['_id']",
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "usetTypeService",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "qrcodeFileName",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['qrcodeFileName']",
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "usetTypeService",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "vendorId",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['vendor_lk']['_id']",
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "usetTypeService",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "userPrefs",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['includePrefs']",
                        "target": "$"
                    }
                ]
            },
            {
                "from_name": "usetTypeService",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "zipCode",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['body']['zip']",
                        "target": "$"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["startScreen_usetTypeService_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [
            {
                "from_name": "userId",
                "from_type": "LOCAL_STORAGE",
                "to_name": "usetTypeService",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['userId']"
                    }
                ]
            }
        ]
    };

    Apperyio.mappings["startScreen_start_menuHeading_list_service_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [
            {
                "from_name": "start_menuHeading_list_service",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "menuHeading",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['body'][i]['heading']",
                        "target": "$[i]['heading']"
                    },
                    {
                        "source": "$['body'][i]['_id']",
                        "target": "$[i]['id']"
                    },
                    {
                        "source": "$['body'][i]['headingDescription']",
                        "target": "$[i]['description']"
                    },
                    {
                        "source": "$['body'][i]['headingParent']['_id']",
                        "target": "$[i]['parent_id']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["startScreen_start_menuHeading_list_service_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [
            {
                "from_name": "sessionToken",
                "from_type": "SESSION_STORAGE",
                "to_name": "start_menuHeading_list_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}"
                    },
                    "parameters": {
                        "include": "vendor,vendor.state,vendor.country,headingParent,headingParent.vendor,headingParent.vendor.state,headingParent.vendor.country,headingParent.headingParent,headingParent.headingParent.vendor,headingParent.headingParent.vendor.state,headingParent.headingParent.vendor.country,headingParent.headingParent.headingParent,headingParent.headingParent.headingParent.vendor,headingParent.headingParent.headingParent.vendor.state,headingParent.headingParent.headingParent.vendor.country,headingParent.headingParent.headingParent.headingParent,headingParent.headingParent.headingParent.headingParent.vendor,headingParent.headingParent.headingParent.headingParent.headingParent",
                        "sort": "order",
                        "where": " {\"vendor\": {\"$inQuery\" : { \"_id\": \"{vendor_id}\"}}}",
                        "limit": "1500"
                    },
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['headers']['X-Appery-Session-Token']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["startScreen_stratScreen_vendor_read_service_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": []
    };
    Apperyio.mappings["startScreen_stratScreen_vendor_read_service_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [
            {
                "from_name": "vendorId",
                "from_type": "SESSION_STORAGE",
                "to_name": "stratScreen_vendor_read_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}"
                    },
                    "parameters": {
                        "include": "state,country"
                    },
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['_id']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["startScreen_strartScreen_mobilebarcode_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": []
    };
    Apperyio.mappings["startScreen_statrScreen_clearOrder_service_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": []
    };
    Apperyio.mappings["startScreen_statrScreen_clearOrder_service_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [
            {
                "to_name": "statrScreen_clearOrder_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "Content-Type": "text/plain"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": []
            }
        ]
    };

    Apperyio.mappings["startScreen_statrScreen_registerCustomerDevice_service_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [
            {
                "from_name": "sessionToken",
                "from_type": "SESSION_STORAGE",
                "to_name": "statrScreen_registerCustomerDevice_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "Content-Type": "text/plain"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['headers']['X-Appery-Session-Token']"
                    }
                ]
            },
            {
                "from_name": "deviceId",
                "from_type": "SESSION_STORAGE",
                "to_name": "statrScreen_registerCustomerDevice_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "Content-Type": "text/plain"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['deviceid']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["startScreen_statrScreen_listPrefTypes_service_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [
            {
                "from_name": "statrScreen_listPrefTypes_service",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "prefType",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['body'][i]",
                        "target": "$[i]"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["startScreen_statrScreen_listPrefTypes_service_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [
            {
                "to_name": "statrScreen_listPrefTypes_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}"
                    },
                    "parameters": {
                        "sort": "num"
                    },
                    "body": null
                },
                "mappings": []
            }
        ]
    };
    Apperyio.mappings["startScreen_startScreen_geolocation_service_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [
            {
                "from_name": "startScreen_geolocation_service",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "coords",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['data']['coords']['latitude']",
                        "target": "$['Latitude']"
                    },
                    {
                        "source": "$['data']['coords']['longitude']",
                        "target": "$['Longitude']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["startScreen_startScreen_geolocation_service_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [
            {
                "to_name": "startScreen_geolocation_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "options": {
                            "maximumAge": 5000,
                            "timeout": 9999,
                            "enableHighAccuracy": true,
                            "watchPosition": false
                        }
                    }
                },
                "mappings": []
            }
        ]
    };
    Apperyio.mappings["startScreen_startScreen_findNearestVendors_service_onsuccess_mapping_1"] = {
        "homeScreen": "startScreen",
        "directions": [
            {
                "from_name": "startScreen_findNearestVendors_service",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "startScreen",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['body'][i]",
                        "target": "$['locationsListItem']"
                    },
                    {
                        "source": "$['body'][i]['businessName']",
                        "target": "$['locationsListItem:text']"
                    },
                    {
                        "source": "$['body'][i]['distance']",
                        "target_transformation": function(value, element) {
                            return value + ' miles'
                        },
                        "target": "$['locationsListItem:counter_value']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["startScreen_startScreen_findNearestVendors_service_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [
            {
                "to_name": "startScreen_findNearestVendors_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}"
                    },
                    "parameters": {
                        "include": "state,country",
                        "limit": "1000",
                        "sort": "_id"
                    },
                    "body": null
                },
                "mappings": [
                    {
                        "target_transformation": function(value) {
                            var c = storageGet('coords');
                            // DEBUG
                            // c = { Latitude: 40.7561241, Longitude: -73.9847552 }; 
                            return JSON.stringify({
                                "featuredDate": null,
                                "disabled": {
                                    "$ne": true
                                },
                                "coords": {
                                    "$nearSphere": [c.Longitude, c.Latitude],
                                    "$maxDistanceInKilometers": 5000
                                }
                            });
                        },
                        "target": "$['parameters']['where']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["startScreen_startScreen_recover_pass_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [
            {
                "from_name": "startScreen_recover_pass",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "startScreen",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['body']['message']",
                        "target": "$['resetpass_msg:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["startScreen_startScreen_recover_pass_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [
            {
                "from_name": "startScreen",
                "from_type": "UI",
                "to_name": "startScreen_recover_pass",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {},
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$['rpw_email:text']",
                        "target": "$['parameters']['username']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["startScreen_startScreen_reset_pass_with_secret_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [
            {
                "from_name": "startScreen_reset_pass_with_secret",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "startScreen",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['body']['message']",
                        "target": "$['resetpass_msg:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["startScreen_startScreen_reset_pass_with_secret_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [
            {
                "from_name": "startScreen",
                "from_type": "UI",
                "to_name": "startScreen_reset_pass_with_secret",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "Content-Type": "text/plain"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$['resetpass_secret:text']",
                        "target": "$['parameters']['secretCode']"
                    },
                    {
                        "source": "$['resetpass_email:text']",
                        "target": "$['parameters']['username']"
                    },
                    {
                        "source": "$['resetpass_new_pass:text']",
                        "target": "$['parameters']['newPassword']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["startScreen_startScreen_findFeaturedVendor_service_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [
            {
                "to_name": "startScreen_findFeaturedVendor_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}"
                    },
                    "parameters": {
                        "include": "state,country",
                        "limit": "1",
                        "sort": "-featuredDate"
                    },
                    "body": null
                },
                "mappings": []
            }
        ]
    };
    Apperyio.mappings["startScreen_startScreen_findFeaturedVendor_service_onsuccess_mapping_1"] = {
        "homeScreen": "startScreen",
        "directions": [
            {
                "from_name": "startScreen_findFeaturedVendor_service",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "startScreen",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['body'][i]",
                        "target": "$['featureLocationsItem']"
                    },
                    {
                        "source": "$['body'][i]['businessName']",
                        "target": "$['featureLocationsItem:text']"
                    },
                    {
                        "source": "$['body'][i]['distance']",
                        "target_transformation": function(value, element) {
                            return 'featured';
                        },
                        "target": "$['featureLocationsItem:counter_value']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.loginService = Apperyio.datasources.loginService = new Apperyio.DataSource(projectMdb1_login_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_loginService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_loginService_onsuccess_mapping_0"]);
            userName = storageGet('userName');
            Settings.session_token = storageGet('sessionToken');
            try {
                usetTypeService.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
            // if(storageGet('wasGuest'))
            if (wasGuest) {
                wasGuest = false;
                //storageSet('wasGuest', false);
            } else {
                storageSet('currentOrder', Apperyio.getModel('currentOrder'));
                //statrScreen_clearOrder_service.execute({});
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            if (jqXHR.responseJSON.code === 'DBUI110') {
                showErrorMessage('We can\'t find ' + Apperyio('loginField').val());
            } else if (jqXHR.responseJSON.code === 'DBUI107') {
                showErrorMessage('Please enter your password');
            } else {
                console.log('Login error: ', jqXHR.responseJSON.description);
                var msg = "Password not correct for login";
                showErrorMessage(msg);
            };
        }
    });
    window.usetTypeService = Apperyio.datasources.usetTypeService = new Apperyio.DataSource(projectMdb1_user_details_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_usetTypeService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_usetTypeService_onsuccess_mapping_0"]);
            try {
                statrScreen_listPrefTypes_service.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
            /* User type found on `startScreen` */
            storageSet('menuHeading', null);
            storageSet('headingSelectList', null);
            storageSet('menuHierarchyList', null);
            // console.log(data);
            //makeHierarchy();
            // console.log(data);
            if (data.userType == "customer") {
                customerMode = true;
            } else {
                customerMode = false;
            }
            if ((!isPhone || !customerMode) && !isGuest) {
                projectMdb1_settings.vendor_id = storageGet('vendorId');
            }
            if (customerMode) {
                if (!isPhone) {
                    var id = urlParam('vendor');
                    if (id) {
                        storageSet('vendorId', id);
                        projectMdb1_settings.user_id = id;
                        projectMdb1_settings.vendor_id = id;
                    }
                }
                /* Save userName and password in xorKey if this is not a guest */
                var userName = storageGet('userName');
                var password = Apperyio('passwordField').val();
                if (userName !== 'guest') {
                    xorKey.save(userName, password);
                }
                /* Register notification channel for guests with accounts */
                if (window.cordova) {
                    storageSet('deviceId', device.uuid);
                    statrScreen_registerCustomerDevice_service.execute({});
                }
            }
            if (projectMdb1_settings.vendor_id) {
                storageSet('vendorId', projectMdb1_settings.vendor_id);
                stratScreen_vendor_read_service.execute({});
            } else {
                if (!customerMode) {
                    Appery.navigateTo('operationsRestaurantPage');
                } else {
                    storageSet('autoLocationPopup', true);
                    Appery.navigateTo('navigatePage');
                }
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.start_menuHeading_list_service = Apperyio.datasources.start_menuHeading_list_service = new Apperyio.DataSource(projectMdb1_menuHeading_list_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_start_menuHeading_list_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_start_menuHeading_list_service_onsuccess_mapping_0"]);
            makeHierarchy();
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.stratScreen_vendor_read_service = Apperyio.datasources.stratScreen_vendor_read_service = new Apperyio.DataSource(projectMdb1_vendor_read_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_stratScreen_vendor_read_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_stratScreen_vendor_read_service_onsuccess_mapping_0"]);
            if (customerMode) {
                Appery.navigateTo('menuPage_v2');
            } else {
                Appery.navigateTo('proprietorStartPage');
            }
        
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.strartScreen_mobilebarcode = Apperyio.datasources.strartScreen_mobilebarcode = new Apperyio.DataSource(zzBarcodeService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_strartScreen_mobilebarcode_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            /* Barcode found on `startScreen`. Get token using `login_service` */
            projectMdb1_settings.vendor_id = null;
            var vendor_id = urlParam('vendor', data.text);
            if (vendor_id) {
                projectMdb1_settings.vendor_id = vendor_id;
                isGuest = true;
                loginService.execute({
                    data: {
                        username: 'guest',
                        password: 'guest'
                    }
                });
            } else {
                navigator.notification.alert("Oops, I didn't see a QR code", null, "Problem");
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            navigator.notification.alert("Oops, I didn't see a QR code", null, "Problem");
        }
    });
    window.statrScreen_clearOrder_service = Apperyio.datasources.statrScreen_clearOrder_service = new Apperyio.DataSource(clearOrder_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_statrScreen_clearOrder_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_statrScreen_clearOrder_service_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.statrScreen_registerCustomerDevice_service = Apperyio.datasources.statrScreen_registerCustomerDevice_service = new Apperyio.DataSource(registerCustomerDevice_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_statrScreen_registerCustomerDevice_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {},
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.statrScreen_listPrefTypes_service = Apperyio.datasources.statrScreen_listPrefTypes_service = new Apperyio.DataSource(projectMdb1_prefType_list_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_statrScreen_listPrefTypes_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_statrScreen_listPrefTypes_service_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.startScreen_geolocation_service = Apperyio.datasources.startScreen_geolocation_service = new Apperyio.DataSource(GeolocationService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_startScreen_geolocation_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_startScreen_geolocation_service_onsuccess_mapping_0"]);
            try {
                startScreen_findNearestVendors_service.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            var error = arguments[2];
            if (error.code == 1) {
                alertMsg(error.message, 'Please turn on your location service to use this feature.');
            } else {
                alertMsg('Geolocation error', error.message);
            };
        }
    });
    window.startScreen_findNearestVendors_service = Apperyio.datasources.startScreen_findNearestVendors_service = new Apperyio.DataSource(projectMdb1_vendor_query_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_startScreen_findNearestVendors_service_onbeforesend_mapping_0"]);
            try {
                startScreen_findFeaturedVendor_service.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            var c = storageGet('coords');
            data.forEach(function(item) {
                var d = getDistance({
                    lat: c.Latitude,
                    lng: c.Longitude
                }, {
                    lat: item.coords[1],
                    lng: item.coords[0]
                });
                item.distance = (d * 0.000621371).toFixed(1);
            });
            data = data.sort(function(a, b) {
                return a.distance - b.distance;
            });
            data = data.slice(0, MAX_RESTRAUNTS_TO_SHOW);
            window.navigatePage_findNearestVendors = data;
            
            Apperyio.datasources["startScreen_findNearestVendors_service"].response = {body: data};
            
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_startScreen_findNearestVendors_service_onsuccess_mapping_1"]);
            var popupElement = Apperyio("locationsPopup");
            if (popupElement.popup("option", "positionTo") === "origin") {
                popupElement.popup("open", {
                    transition: "pop",
                    positionTo: "#" + $(this).attr("id")
                });
            } else {
                popupElement.popup("open", {
                    transition: "pop"
                });
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            hideSpinner();
            console.log('--- Geolocation error:', errorThrown);
            console.log('textStatus:', textStatus);
            alertMsg('Error', 'Geolocation error');
        }
    });
    window.startScreen_recover_pass = Apperyio.datasources.startScreen_recover_pass = new Apperyio.DataSource(Reset_Pass_Twilio_SendSMS, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_startScreen_recover_pass_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_startScreen_recover_pass_onsuccess_mapping_0"]);
            Apperyio('recoverpassword_popup').popup('close');
            var popupElement = Apperyio("resetpassword_popup");
            if (popupElement.popup("option", "positionTo") === "origin") {
                popupElement.popup("open", {
                    transition: "slideup",
                    positionTo: "#" + $(this).attr("id")
                });
            } else {
                popupElement.popup("open", {
                    transition: "slideup"
                });
            };
            Appery("resetpass_email").val("");
            Appery("resetpass_secret").val("");
            Appery("resetpass_new_pass").val("");
            Appery("resetpass_confirm_pass").val("");
            Appery("resetpass_response_error").html("");
            Appery("resetpass_email_error").html("");
            Appery("resetpass_secret_error").html("");
            Appery("resetpass_pass_error").html("");
            setTimeout(function() {
                Apperyio('resetpassword_popup').popup('open');
            }, 1000);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            var error = jqXHR.responseJSON.message;
            //Appery.io
            //showErrorMessage(error);
            Apperyio('rpw_error').show();
            Apperyio('rpw_error').html(error);
            ;
        }
    });
    window.startScreen_reset_pass_with_secret = Apperyio.datasources.startScreen_reset_pass_with_secret = new Apperyio.DataSource(Reset_Password_With_Secret_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_startScreen_reset_pass_with_secret_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_startScreen_reset_pass_with_secret_onsuccess_mapping_0"]);
            toggle('startScreen_resetpass_submit', 'mob', 'false');
            toggle('startScreen_resetpass_secret', 'mob', 'false');
            toggle('startScreen_resetpass_new_pass', 'mob', 'false');
            toggle('startScreen_resetpass_confirm_pass', 'mob', 'false');
            toggle('startScreen_resetpass_email', 'mob', 'false');
            toggle('startScreen_resetpass_response_error', 'mob', 'false');
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            var error = jqXHR.responseJSON.message;
            //Appery.io
            //showErrorMessage(error);
            Apperyio('resetpass_response_error').show();
            Apperyio('resetpass_response_error').html(error);
            ;
        }
    });
    window.startScreen_findFeaturedVendor_service = Apperyio.datasources.startScreen_findFeaturedVendor_service = new Apperyio.DataSource(projectMdb1_vendor_query_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_startScreen_findFeaturedVendor_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            window.navigatePage_findFeaturedVendors = data;
            Apperyio('featureLocationList').css('display', data.length > 0 ? 'block' : 'none');
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_startScreen_findFeaturedVendor_service_onsuccess_mapping_1"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    /*
     * Appery.io Push-notification registration service
     */
    Apperyio.mappings["_pushRegistrationApperyService_onbeforesend"] = {
        "homeScreen": "startScreen",
        "directions": [{
                "from_name": "pushNotificationToken",
                "from_type": "LOCAL_STORAGE",
                "to_name": "_registerPushApperyDS",
                "to_type": "SERVICE_REQUEST",
                "mappings": [{
                    "source": "$",
                    "target": "$['body']['token']"
                }]
            },
            {
                "from_name": "pushNotificationDeviceID",
                "from_type": "LOCAL_STORAGE",
                "to_name": "_registerPushApperyDS",
                "to_type": "SERVICE_REQUEST",
                "mappings": [{
                    "source": "$",
                    "target": "$['body']['deviceID']"
                }]
            },
            {
                "from_name": "deviceTimeZone",
                "from_type": "LOCAL_STORAGE",
                "to_name": "_registerPushApperyDS",
                "to_type": "SERVICE_REQUEST",
                "mappings": [{
                    "source": "$",
                    "target": "$['body']['timeZone']"
                }]
            },
            {
                "to_name": "_registerPushApperyDS",
                "to_type": "SERVICE_REQUEST",
                "mappings": [{
                        "target_transformation": function(value) {
                            return Apperyio.getProjectGUID();
                        },
                        "target": "$['headers']['X-Appery-App-Id']"
                    },
                    {
                        "target_transformation": function(value) {
                            return Apperyio.getTargetPlatform();
                        },
                        "target": "$['body']['type']"
                    }
                ]
            }
        ]
    };
    var _registerPushApperyDS = Apperyio.datasources._registerPushApperyDS = new Apperyio.DataSource(_pushRegistrationApperyService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["_pushRegistrationApperyService_onbeforesend"]);
        },
        'onComplete': function(jqXHR, textStatus) {},
        'onSuccess': function(data) {
            console.info('App successfully registered with Appery.io Push service');
            $(document).trigger('pushregistrationsuccess');
        },
        'onError': function(jqXHR, textStatus, errorThrown) {
            $(document).trigger('pushregistrationfail');
        }
    });
    Apperyio.CurrentScreen = 'startScreen';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var startScreen_onLoad = function() {
        startScreen_elementsExtraJS();
        startScreen_deviceEvents();
        startScreen_windowEvents();
        startScreen_elementsEvents();
    };
    // screen window events
    function startScreen_windowEvents() {
        $('#startScreen').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#startScreen').on({
            pageshow: function(event) {
                try {
                    $a.storage["vendorId"].update("$", "null")
                } catch (e) {
                    console.error(e)
                };
                try {
                    $a.storage["sessionToken"].update("$", "null")
                } catch (e) {
                    console.error(e)
                };
                try {
                    $a.storage["userId"].update("$", "null")
                } catch (e) {
                    console.error(e)
                };
                try {
                    $a.storage["userType"].update("$", "null")
                } catch (e) {
                    console.error(e)
                };
                // apply rounded corners to input fields
                Apperyio('loginField').parent().addClass('rounded-input');
                Apperyio('passwordField').parent().addClass('rounded-input');
                storageSet('currentVendor', '');
                storageSet('menuHierarchyList', null);
                Apperyio('startContainer').hide();
                if (navigator.userAgent.match(/(iPhone|iPod|iPad|Android|BlackBerry|IEMobile)/)) {
                    isPhone = true;
                }
                if (navigator.userAgent.match(/(iPhone|iPad)/)) {
                    isApple = true;
                }
                projectMdb1_settings.vendor_id = null;
                var vendor_id = urlParam('vendor');
                if (vendor_id) {
                    var currentVendor = {};
                    currentVendor.id = vendor_id;
                    storageSet('currentVendor', currentVendor);
                    storageSet('vendorId', vendor_id);
                    projectMdb1_settings.vendor_id = vendor_id;
                    //    startScreen_vendor_details_get.execute();
                } else {
                    isGuest = false;
                    var skipPage = false;
                    if (storageGet('userName') === 'guest') {
                        //storageSet('wasGuest', true);
                        wasGuest = true;
                    } else {
                        // Bypass login screen if we have xorKey available
                        if (xorKey.available()) {
                            Apperyio('loginField').val(xorKey.getLogin());
                            Apperyio('passwordField').val(xorKey.getPassword());
                            loginService.execute();
                            skipPage = true;
                        }
                    }
                    if (!skipPage) {
                        Apperyio('startContainer').show();
                        if (!storageGet('dontShowIntro')) {
                            setTimeout(function() {
                                Apperyio('introPopup').popup('open');
                            }, 1000);
                        } else {
                            setTimeout(function() {
                                startScreen_geolocation_service.execute();
                            }, 1000);
                        }
                    }
                }
                // PM-348
                var isIPhone = navigator.userAgent.indexOf('Mac OS X') != -1;
                $('.loginForm input').after($('<span class="clean-btn">&times;</span>').css('top', isIPhone ? '-4px' : '-2px').on('click', function() {
                    $(this).prev().val('');
                }));
                ;
            },
        });
    };
    // device events
    function startScreen_deviceEvents() {
        document.addEventListener("deviceready", function() {
            initialize_StatusBar_plugin();
            $(document).bind("pushinit", function() {
                localStorage.setItem('pushNotificationToken', arguments[1].registrationId);
                _registerPushApperyDS.execute({});
            });
            localStorage.setItem('pushNotificationDeviceID', device.uuid);
            var offset = new Date().getTimezoneOffset();
            var hr = parseInt(offset / (-60));
            var min = -offset - hr * 60;
            var tmin = '' + min;
            var timezone = 'UTC' + (hr > 0 ? '+' + hr : hr) + ':' + (tmin.length > 1 ? tmin : '0' + tmin);
            localStorage.setItem('deviceTimeZone', timezone);
            var push = PushNotification.init({
                ios: {
                    alert: true,
                    badge: false,
                    sound: true,
                    clearBadge: true
                },
                android: {
                    senderID: '909555174741'
                }
            });
            push.on('registration', function(data) {
                $(document).trigger('pushinit', data);
            });
            push.on('notification', function(data) {
                $(document).trigger('push-notification', data);
            });
            push.on('error', function(e) {
                console.log("Error: " + e.message);
            });
        });
    };
    // screen elements extra js
    function startScreen_elementsExtraJS() {
        // screen (startScreen) extra code
        /* introPopup */
        $("#startScreen_introPopup").popup("option", "positionTo", "window");
        /* createAccountPopup */
        $("#startScreen_createAccountPopup").popup("option", "positionTo", "window");
        /* accountTypeList */
        listView = $("#startScreen_accountTypeList");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#startScreen_accountTypeList .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        /* personSelectButton */
        /* proprietorSelectButton */
        /* forgotPasswordPopup */
        $("#startScreen_forgotPasswordPopup").popup("option", "positionTo", "window");
        /* locationsPopup */
        $("#startScreen_locationsPopup").popup("option", "positionTo", "window");
        /* featureLocationList */
        listView = $("#startScreen_featureLocationList");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#startScreen_featureLocationList .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        /* featureLocationsItem */
        /* locationList */
        listView = $("#startScreen_locationList");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#startScreen_locationList .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        /* locationsListItem */
        /* recoverpassword_popup */
        $("#startScreen_recoverpassword_popup").popup("option", "positionTo", "window");
        /* resetpassword_popup */
        $("#startScreen_resetpassword_popup").popup("option", "positionTo", "window");
    };
    // screen elements handler
    function startScreen_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#startScreen_startHeader [name="helpButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('helpPage', {
                        transition: 'pop',
                        reverse: false
                    });
                }
            },
        }, '#startScreen_startHeader [name="helpButton"]');
        $(document).off("click", '#startScreen_startContainer [name="knowyeLogo"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('aboutPage', {
                        transition: 'flip',
                        reverse: false
                    });
                }
            },
        }, '#startScreen_startContainer [name="knowyeLogo"]');
        $(document).off("click", '#startScreen_startContainer [name="scanMenuCodeButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        strartScreen_mobilebarcode.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                }
            },
        }, '#startScreen_startContainer [name="scanMenuCodeButton"]');
        $(document).off("click", '#startScreen_startContainer [name="gotoSearch"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        startScreen_geolocation_service.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                }
            },
        }, '#startScreen_startContainer [name="gotoSearch"]');
        $(document).off("input", '#startScreen_startContainer [name="loginField"]').on({
            input: function(event) {
                Apperyio('errorLabel').hide();
            },
        }, '#startScreen_startContainer [name="loginField"]');
        $(document).off("click", '#startScreen_startContainer [name="loginButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    xorKey.remove();
                    isGuest = false;
                    if (verifyEmail()) {
                        loginService.execute({});
                    };
                }
            },
        }, '#startScreen_startContainer [name="loginButton"]');
        $(document).off("click", '#startScreen_startContainer [name="forgotPwLabel"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var popupElement = Apperyio("recoverpassword_popup");
                    if (popupElement.popup("option", "positionTo") === "origin") {
                        popupElement.popup("open", {
                            transition: "slidedown",
                            positionTo: "#" + $(this).attr("id")
                        });
                    } else {
                        popupElement.popup("open", {
                            transition: "slidedown"
                        });
                    };
                    Appery("rpw_email").val("");
                }
            },
        }, '#startScreen_startContainer [name="forgotPwLabel"]');
        $(document).off("click", '#startScreen_startContainer [name="createAccountButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('createAccount', {
                        reverse: false
                    });
                    projectMdb1_settings.vendor_id = null;
                }
            },
        }, '#startScreen_startContainer [name="createAccountButton"]');
        $(document).off("click", '#startScreen_startContainer [name="touLabel"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('touPage', {
                        transition: 'flip',
                        reverse: false
                    });
                }
            },
        }, '#startScreen_startContainer [name="touLabel"]');
        $(document).off("click", '#startScreen_startContainer [name="privacyLabel"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    window.open('https://www.iubenda.com/privacy-policy/7831739', 'NewWindow', 'width=600,height=400,toolbar=yes,location=yes,directories=yes,status=yes,menubar=yes,scrollbars=yes,copyhistory=yes,resizable=yes');
                }
            },
        }, '#startScreen_startContainer [name="privacyLabel"]');
        $(document).off("click", '#startScreen_introPopup [name="introPopupContinueButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    if (Apperyio('showAgainCheck').find('input').prop('checked')) {
                        storageSet('dontShowIntro', true);
                    }
                    Apperyio('introPopup').popup('close');
                    startScreen_geolocation_service.execute();;
                }
            },
        }, '#startScreen_introPopup [name="introPopupContinueButton"]');
        $(document).off("click", '#startScreen_forgotPasswordPopup [name="resetPwButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('forgotPasswordPopup').popup('close');
                }
            },
        }, '#startScreen_forgotPasswordPopup [name="resetPwButton"]');
        $(document).off("click", '#startScreen_locationsPopup [name="locationsCloseBtn"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('locationsPopup').popup('close');
                }
            },
        }, '#startScreen_locationsPopup [name="locationsCloseBtn"]');
        $(document).off("click", '#startScreen_locationsPopup [name="featureLocationsItem"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    proceedAsGuest(loginService, this, window.navigatePage_findFeaturedVendors, true);
                }
            },
        }, '#startScreen_locationsPopup [name="featureLocationsItem"]');
        $(document).off("click", '#startScreen_locationsPopup [name="locationsListItem"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    proceedAsGuest(loginService, this, window.navigatePage_findNearestVendors, true);
                }
            },
        }, '#startScreen_locationsPopup [name="locationsListItem"]');
        $(document).off("click", '#startScreen_recoverpassword_popup [name="rpw_close_btn"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('recoverpassword_popup').popup('close');
                    toggle('startScreen_rpw_error', 'mob', 'false');
                    Appery('rpw_email').val("");
                    Appery('rpw_error').html("");
                }
            },
        }, '#startScreen_recoverpassword_popup [name="rpw_close_btn"]');
        $(document).off("change", '#startScreen_recoverpassword_popup [name="rpw_email"]').on({
            change: function(event) {
                verifyEmail(Appery('rpw_email').val(), Appery('rpw_error'));
            },
        }, '#startScreen_recoverpassword_popup [name="rpw_email"]');
        $(document).off("click", '#startScreen_recoverpassword_popup [name="rpw_send_code"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    toggle('startScreen_rpw_error', 'mob', 'false');
                    if (verifyEmail(Appery('rpw_email').val(), Appery('rpw_error'))) {
                        startScreen_recover_pass.execute({});
                    };
                }
            },
        }, '#startScreen_recoverpassword_popup [name="rpw_send_code"]');
        $(document).off("click", '#startScreen_resetpassword_popup [name="resetpass_close_btn"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('resetpassword_popup').popup('close');
                }
            },
        }, '#startScreen_resetpassword_popup [name="resetpass_close_btn"]');
        $(document).off("click", '#startScreen_resetpassword_popup [name="resetpass_submit"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var shallExecuteQuery = true;
                    if (!isStrongPassword(Appery('resetpass_new_pass').val(),
                            Appery('resetpass_confirm_pass').val(), Appery('resetpass_pass_error'))) {
                        shallExecuteQuery = false;
                    }
                    if (Appery('resetpass_email').val().length <= 0) {
                        showErrorMessage('email cannot be empty', Appery('resetpass_email_error'));
                        shallExecuteQuery = false;
                    } else {
                        if (!verifyEmail(Appery('resetpass_email').val(), Appery('resetpass_email_error'))) {
                            shallExecuteQuery = false;
                        }
                    }
                    if (!isValidSecret(Appery('resetpass_secret').val(), Appery('resetpass_secret_error'))) {
                        shallExecuteQuery = false;
                    }
                    if (shallExecuteQuery) {
                        startScreen_reset_pass_with_secret.execute({});
                    };
                    toggle('startScreen_resetpass_response_error', 'mob', 'false');
                }
            },
        }, '#startScreen_resetpassword_popup [name="resetpass_submit"]');
    };
    $(document).off("pagebeforeshow", "#startScreen").on("pagebeforeshow", "#startScreen", function(event, ui) {
        Apperyio.CurrentScreen = "startScreen";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    startScreen_onLoad();
};
$(document).off("pagecreate", "#startScreen").on("pagecreate", "#startScreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    startScreen_js();
});