/*
 * JS for wishListPage generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '148444cb-eb26-4cec-bc22-29bf794bc529';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "itemPage",
    "location": "itemPage.html"
},{
    "name": "menu_shared",
    "location": "menu_shared.html"
}, {
    "name": "zzqrCodePage",
    "location": "zzqrCodePage.html"
}, {
    "name": "zzfacebookLogin",
    "location": "zzfacebookLogin.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "zzpromoManage",
    "location": "zzpromoManage.html"
}, {
    "name": "aboutPage",
    "location": "aboutPage.html"
}, {
    "name": "itemDetailsPage",
    "location": "itemDetailsPage.html"
}, {
    "name": "menuHeadingManagePage",
    "location": "menuHeadingManagePage.html"
}, {
    "name": "createAccount",
    "location": "createAccount.html"
}, {
    "name": "zzsettingsPage",
    "location": "zzsettingsPage.html"
}, {
    "name": "wishListPage",
    "location": "wishListPage.html"
}, {
    "name": "menuManagementPage",
    "location": "menuManagementPage.html"
}, {
    "name": "favoritesPage",
    "location": "favoritesPage.html"
}, {
    "name": "touPage",
    "location": "touPage.html"
}, {
    "name": "navigatePage",
    "location": "navigatePage.html"
}, {
    "name": "logoutPage",
    "location": "logoutPage.html"
}, {
    "name": "proprietorPage",
    "location": "proprietorPage.html"
}, {
    "name": "helpPage",
    "location": "helpPage.html"
}, {
    "name": "proprietorAnalyticsPage",
    "location": "proprietorAnalyticsPage.html"
}, {
    "name": "menuPreviewPage",
    "location": "menuPreviewPage.html"
}, {
    "name": "zzpromoEdit",
    "location": "zzpromoEdit.html"
}, {
    "name": "menuPage_v2",
    "location": "menuPage_v2.html"
}, {
    "name": "filterPage",
    "location": "filterPage.html"
}, {
    "name": "easterEggPage",
    "location": "easterEggPage.html"
}, {
    "name": "profilePage",
    "location": "profilePage.html"
}, {
    "name": "zzsearchPage",
    "location": "zzsearchPage.html"
}, {
    "name": "itemEditPage",
    "location": "itemEditPage.html"
}, {
    "name": "zzproprietorStatPage",
    "location": "zzproprietorStatPage.html"
}, {
    "name": "zzdetailedReviewPage",
    "location": "zzdetailedReviewPage.html"
}, {
    "name": "selectionHistoryPage",
    "location": "selectionHistoryPage.html"
}, {
    "name": "operationsRestaurantPage",
    "location": "operationsRestaurantPage.html"
}, {
    "name": "itemManagePage",
    "location": "itemManagePage.html"
}, {
    "name": "proprietorStartPage",
    "location": "proprietorStartPage.html"
}, {
    "name": "orderHistoryPage",
    "location": "orderHistoryPage.html"
}, {
    "name": "selectedPage",
    "location": "selectedPage.html"
}, {
    "name": "faqPage",
    "location": "faqPage.html"
}, {
    "name": "zzratingInfoPage",
    "location": "zzratingInfoPage.html"
}, {
    "name": "zztimeRangePage",
    "location": "zztimeRangePage.html"
}, {
    "name": "zzscannerPage",
    "location": "zzscannerPage.html"
}, {
    "name": "zzCSStestPage",
    "location": "zzCSStestPage.html"
}, {
    "name": "menuHistoryPage",
    "location": "menuHistoryPage.html"
}, {
    "name": "zzmenuPage",
    "location": "zzmenuPage.html"
}, {
    "name": "zzitemInventoryPage",
    "location": "zzitemInventoryPage.html"
}, {
    "name": "zzalertPage",
    "location": "zzalertPage.html"
}];

function wishListPage_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'menuButton': 'wishListPage_menuButton',
        'wishListLabel': 'wishListPage_wishListLabel',
        'wishList': 'wishListPage_wishList',
        'wish': 'wishListPage_wish',
        'itemLabel': 'wishListPage_itemLabel',
        'mobilelistitembutton_4': 'wishListPage_mobilelistitembutton_4',
        'noteGrid': 'wishListPage_noteGrid',
        'noteLabelCell': 'wishListPage_noteLabelCell',
        'noteLabel': 'wishListPage_noteLabel',
        'noteLabelTextCell': 'wishListPage_noteLabelTextCell',
        'noteLabelText': 'wishListPage_noteLabelText',
        'proprietorLabel': 'wishListPage_proprietorLabel',
        'deleteConfirmLabel': 'wishListPage_deleteConfirmLabel',
        'deleteButtonGrid': 'wishListPage_deleteButtonGrid',
        'deleteConfirmCell': 'wishListPage_deleteConfirmCell',
        'deleteConfirmButton': 'wishListPage_deleteConfirmButton',
        'deleteCancelCell': 'wishListPage_deleteCancelCell',
        'deleteCancelButton': 'wishListPage_deleteCancelButton'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["wishListPage_wishlistPage_wishlist_query_service_onbeforesend_mapping_0"] = {
        "homeScreen": "wishListPage",
        "directions": [
            {
                "from_name": "userId",
                "from_type": "LOCAL_STORAGE",
                "to_name": "wishlistPage_wishlist_query_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}"
                    },
                    "parameters": {
                        "include": "item,item.cuisine_lk,item.ingredientMain_lk,item.ingredientMain_lk.category_lk,item.ingredientHidden_lk,item.ingredientHidden_lk.category_lk,item.ingredientFeatured_lk,item.ingredientFeatured_lk.category_lk,item.rating_lk,item.rating_lk.item,item.rating_lk.item.cuisine_lk,item.rating_lk.item.ingredientMain_lk,item.rating_lk.item.ingredientHidden_lk,item.rating_lk.item.ingredientFeatured_lk,item.rating_lk.item.rating_lk,item.rating_lk.item.vendor_lk,item.rating_lk.item.heading,item.rating_lk.user,item.rating_lk.user.status,item.rating_lk.user.vendor_lk,item.vendor_lk,item.vendor_lk.state,item.vendor_lk.country,item.heading,item.heading.vendor,item.heading.headingParent,item.heading.owner_lk",
                        "limit": "1500"
                    },
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target_transformation": function(value) {
                            return {
                                "user": {
                                    "$inQuery": {
                                        "_id": value
                                    }
                                },
                                "item": {
                                    "$inQuery": {
                                        "vendor_lk": {
                                            "$inQuery": {
                                                "disabled": {
                                                    "$ne": true
                                                }
                                            }
                                        }
                                    }
                                }
                            };
                        },
                        "target": "$['parameters']['where']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["wishListPage_wishlistPage_wishlist_query_service_onsuccess_mapping_0"] = {
        "homeScreen": "wishListPage",
        "directions": [
            {
                "from_name": "wishlistPage_wishlist_query_service",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "wishListPage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['body'][i]",
                        "target_transformation": function(value, element) {
                            element.prop('item_id', value.item._id);
                            element.prop('wl_item_id', value._id);
                        },
                        "target": "$['wish']"
                    },
                    {
                        "source": "$['body'][i]['item']['name']",
                        "target": "$['wish']['itemLabel:text']"
                    },
                    {
                        "source": "$['body'][i]['item']['vendor_lk']['businessName']",
                        "target": "$['wish']['proprietorLabel:text']"
                    },
                    {
                        "source": "$['body'][i]['notes']",
                        "target": "$['wish']['noteLabelText:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["wishListPage_wishlistPage_wishlist_delete_service_onbeforesend_mapping_0"] = {
        "homeScreen": "wishListPage",
        "directions": [
            {
                "from_name": "selectedItem",
                "from_type": "SESSION_STORAGE",
                "to_name": "wishlistPage_wishlist_delete_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}"
                    },
                    "parameters": {},
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['_id']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.wishlistPage_wishlist_query_service = Apperyio.datasources.wishlistPage_wishlist_query_service = new Apperyio.DataSource(projectMdb1_wishlist_query_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["wishListPage_wishlistPage_wishlist_query_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["wishListPage_wishlistPage_wishlist_query_service_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.wishlistPage_wishlist_delete_service = Apperyio.datasources.wishlistPage_wishlist_delete_service = new Apperyio.DataSource(projectMdb1_wishlist_delete_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["wishListPage_wishlistPage_wishlist_delete_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio('deleteConfirmPopup').popup('close');
            try {
                wishlistPage_wishlist_query_service.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'wishListPage';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var wishListPage_onLoad = function() {
        wishListPage_elementsExtraJS();
        try {
            wishlistPage_wishlist_query_service.execute({});
        } catch (e) {
            console.error(e);
            hideSpinner();
        };
        wishListPage_deviceEvents();
        wishListPage_windowEvents();
        wishListPage_elementsEvents();
    };
    // screen window events
    function wishListPage_windowEvents() {
        $('#wishListPage').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function wishListPage_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function wishListPage_elementsExtraJS() {
        // screen (wishListPage) extra code
        /* wishList */
        listView = $("#wishListPage_wishList");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#wishListPage_wishList .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        /* wish */
        /* deleteConfirmPopup */
        $("#wishListPage_deleteConfirmPopup").popup("option", "positionTo", "window");
    };
    // screen elements handler
    function wishListPage_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#wishListPage_wishlistHeader [name="menuButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('navigatePage', {
                        transition: 'slidedown',
                        reverse: false
                    });
                }
            },
        }, '#wishListPage_wishlistHeader [name="menuButton"]');
        $(document).off("click taphold change", '#wishListPage_wishlistContainer [name="wish"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    storageSet('selectedItem', this.item_id);
                    Apperyio.navigateTo('itemDetailsPage', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
            taphold: function(event) {
                storageSet('selectedItem', this.wl_item_id);
                var popupElement = Apperyio("deleteConfirmPopup");
                if (popupElement.popup("option", "positionTo") === "origin") {
                    popupElement.popup("open", {
                        transition: "slide",
                        positionTo: "#" + $(this).attr("id")
                    });
                } else {
                    popupElement.popup("open", {
                        transition: "slide"
                    });
                };
            },
            change: function(event) {
                var popupElement = Apperyio("deleteConfirmPopup");
                if (popupElement.popup("option", "positionTo") === "origin") {
                    popupElement.popup("open", {
                        transition: "slide",
                        positionTo: "#" + $(this).attr("id")
                    });
                } else {
                    popupElement.popup("open", {
                        transition: "slide"
                    });
                };
            },
        }, '#wishListPage_wishlistContainer [name="wish"]');
        $(document).off("click", '#wishListPage_deleteConfirmPopup [name="deleteConfirmButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        wishlistPage_wishlist_delete_service.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                }
            },
        }, '#wishListPage_deleteConfirmPopup [name="deleteConfirmButton"]');
        $(document).off("click", '#wishListPage_deleteConfirmPopup [name="deleteCancelButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('deleteConfirmPopup').popup('close');
                }
            },
        }, '#wishListPage_deleteConfirmPopup [name="deleteCancelButton"]');
    };
    $(document).off("pagebeforeshow", "#wishListPage").on("pagebeforeshow", "#wishListPage", function(event, ui) {
        Apperyio.CurrentScreen = "wishListPage";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    wishListPage_onLoad();
};
$(document).off("pagecreate", "#wishListPage").on("pagecreate", "#wishListPage", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    wishListPage_js();
});