/*
 * JS for zzmenuPage generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '148444cb-eb26-4cec-bc22-29bf794bc529';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "itemPage",
    "location": "itemPage.html"
}, {
    "name": "zzqrCodePage",
    "location": "zzqrCodePage.html"
}, {
    "name": "zzfacebookLogin",
    "location": "zzfacebookLogin.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "zzpromoManage",
    "location": "zzpromoManage.html"
}, {
    "name": "aboutPage",
    "location": "aboutPage.html"
}, {
    "name": "itemDetailsPage",
    "location": "itemDetailsPage.html"
}, {
    "name": "menuHeadingManagePage",
    "location": "menuHeadingManagePage.html"
}, {
    "name": "createAccount",
    "location": "createAccount.html"
}, {
    "name": "zzsettingsPage",
    "location": "zzsettingsPage.html"
}, {
    "name": "wishListPage",
    "location": "wishListPage.html"
}, {
    "name": "menuManagementPage",
    "location": "menuManagementPage.html"
}, {
    "name": "favoritesPage",
    "location": "favoritesPage.html"
}, {
    "name": "touPage",
    "location": "touPage.html"
}, {
    "name": "navigatePage",
    "location": "navigatePage.html"
}, {
    "name": "logoutPage",
    "location": "logoutPage.html"
}, {
    "name": "proprietorPage",
    "location": "proprietorPage.html"
}, {
    "name": "helpPage",
    "location": "helpPage.html"
}, {
    "name": "proprietorAnalyticsPage",
    "location": "proprietorAnalyticsPage.html"
}, {
    "name": "menuPreviewPage",
    "location": "menuPreviewPage.html"
}, {
    "name": "zzpromoEdit",
    "location": "zzpromoEdit.html"
}, {
    "name": "menuPage_v2",
    "location": "menuPage_v2.html"
}, {
    "name": "filterPage",
    "location": "filterPage.html"
}, {
    "name": "easterEggPage",
    "location": "easterEggPage.html"
}, {
    "name": "profilePage",
    "location": "profilePage.html"
}, {
    "name": "zzsearchPage",
    "location": "zzsearchPage.html"
}, {
    "name": "itemEditPage",
    "location": "itemEditPage.html"
}, {
    "name": "zzproprietorStatPage",
    "location": "zzproprietorStatPage.html"
}, {
    "name": "zzdetailedReviewPage",
    "location": "zzdetailedReviewPage.html"
}, {
    "name": "selectionHistoryPage",
    "location": "selectionHistoryPage.html"
}, {
    "name": "operationsRestaurantPage",
    "location": "operationsRestaurantPage.html"
}, {
    "name": "itemManagePage",
    "location": "itemManagePage.html"
}, {
    "name": "proprietorStartPage",
    "location": "proprietorStartPage.html"
}, {
    "name": "orderHistoryPage",
    "location": "orderHistoryPage.html"
}, {
    "name": "selectedPage",
    "location": "selectedPage.html"
}, {
    "name": "faqPage",
    "location": "faqPage.html"
}, {
    "name": "zzratingInfoPage",
    "location": "zzratingInfoPage.html"
}, {
    "name": "zztimeRangePage",
    "location": "zztimeRangePage.html"
}, {
    "name": "zzscannerPage",
    "location": "zzscannerPage.html"
}, {
    "name": "zzCSStestPage",
    "location": "zzCSStestPage.html"
}, {
    "name": "menuHistoryPage",
    "location": "menuHistoryPage.html"
}, {
    "name": "zzmenuPage",
    "location": "zzmenuPage.html"
}, {
    "name": "zzitemInventoryPage",
    "location": "zzitemInventoryPage.html"
}, {
    "name": "zzalertPage",
    "location": "zzalertPage.html"
}];

function zzmenuPage_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'navigateButton': 'zzmenuPage_navigateButton',
        'profileUseGrid': 'zzmenuPage_profileUseGrid',
        'profileUseLabelCell': 'zzmenuPage_profileUseLabelCell',
        'profileUseLabel': 'zzmenuPage_profileUseLabel',
        'profileUseToggleCell': 'zzmenuPage_profileUseToggleCell',
        'profileUseToggle': 'zzmenuPage_profileUseToggle',
        'collapseExpandCell': 'zzmenuPage_collapseExpandCell',
        'collapseExpandButton': 'zzmenuPage_collapseExpandButton',
        'profileSearchGrid': 'zzmenuPage_profileSearchGrid',
        'profileLabelCell': 'zzmenuPage_profileLabelCell',
        'profileToggleCell': 'zzmenuPage_profileToggleCell',
        'searchLabelCell': 'zzmenuPage_searchLabelCell',
        'searchInput': 'zzmenuPage_searchInput',
        'searchButtonCell': 'zzmenuPage_searchButtonCell',
        'searchMenuButton': 'zzmenuPage_searchMenuButton',
        'menuTagLine': 'zzmenuPage_menuTagLine',
        'menuList': 'zzmenuPage_menuList',
        'headingItem': 'zzmenuPage_headingItem',
        'menuHeadingName': 'zzmenuPage_menuHeadingName',
        'mobilelistitembutton_38': 'zzmenuPage_mobilelistitembutton_38',
        'menuHeadingDescription': 'zzmenuPage_menuHeadingDescription',
        'priceRatingGrid': 'zzmenuPage_priceRatingGrid',
        'priceCell': 'zzmenuPage_priceCell',
        'priceGrid': 'zzmenuPage_priceGrid',
        'dollarSignCell': 'zzmenuPage_dollarSignCell',
        'dollarSignLabel': 'zzmenuPage_dollarSignLabel',
        'priceAmountCell': 'zzmenuPage_priceAmountCell',
        'priceAmountLabel': 'zzmenuPage_priceAmountLabel',
        'ratingCell': 'zzmenuPage_ratingCell',
        'selectItemButton': 'zzmenuPage_selectItemButton',
        'addWishListButton': 'zzmenuPage_addWishListButton',
        'unavailableLabel': 'zzmenuPage_unavailableLabel',
        'footerGrid': 'zzmenuPage_footerGrid',
        'selectedCell': 'zzmenuPage_selectedCell',
        'selectedButton': 'zzmenuPage_selectedButton',
        'callServerCell': 'zzmenuPage_callServerCell',
        'callServerButton': 'zzmenuPage_callServerButton',
        'ownerInfoCell': 'zzmenuPage_ownerInfoCell',
        'ownerInfoButton': 'zzmenuPage_ownerInfoButton',
        'categoryAddLabel': 'zzmenuPage_categoryAddLabel',
        'headingAddField': 'zzmenuPage_headingAddField',
        'headerDescriptionField': 'zzmenuPage_headerDescriptionField',
        'categoryParentLabel': 'zzmenuPage_categoryParentLabel',
        'headingExampleLabel1': 'zzmenuPage_headingExampleLabel1',
        'headingExampleLabel2': 'zzmenuPage_headingExampleLabel2',
        'headingExampleLabel3': 'zzmenuPage_headingExampleLabel3',
        'headingParentSelect': 'zzmenuPage_headingParentSelect',
        'headingParentSelect-0': 'zzmenuPage_headingParentSelect-0',
        'headingAddSaveButton': 'zzmenuPage_headingAddSaveButton',
        'categoryEditLabel': 'zzmenuPage_categoryEditLabel',
        'mobiletextinput_22': 'zzmenuPage_mobiletextinput_22',
        'categoryParentEditLabel': 'zzmenuPage_categoryParentEditLabel',
        'categoryParentEditButton': 'zzmenuPage_categoryParentEditButton',
        'categoryParentEditButton-0': 'zzmenuPage_categoryParentEditButton-0',
        'categoryEditSaveButton': 'zzmenuPage_categoryEditSaveButton',
        'itemIsInOrderLabel': 'zzmenuPage_itemIsInOrderLabel',
        'addtoOrderLabel': 'zzmenuPage_addtoOrderLabel',
        'labelStandard': 'zzmenuPage_labelStandard',
        'wishListNote': 'zzmenuPage_wishListNote',
        'closePopupButton': 'zzmenuPage_closePopupButton',
        'wishlistConfirmLabel': 'zzmenuPage_wishlistConfirmLabel',
        'wishListContainsItemLabel': 'zzmenuPage_wishListContainsItemLabel',
        'loginGotoLabel': 'zzmenuPage_loginGotoLabel',
        'loginGotoButtonGrid': 'zzmenuPage_loginGotoButtonGrid',
        'loginGotoCell': 'zzmenuPage_loginGotoCell',
        'loginGotoButton': 'zzmenuPage_loginGotoButton',
        'loginGotoCancelCell': 'zzmenuPage_loginGotoCancelCell',
        'loginGotoCancelButton': 'zzmenuPage_loginGotoCancelButton'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["zzmenuPage_zzmenuPage_onload_mapping_3"] = {
        "homeScreen": "zzmenuPage",
        "directions": [
            {
                "from_name": "currentVendor",
                "from_type": "SESSION_STORAGE",
                "to_name": "zzmenuPage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['menuTagLine']",
                        "target_transformation": function(value, element) {
                            return value || "";
                        },
                        "target": "$['menuTagLine:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["zzmenuPage_menuPage_list_service_onsuccess_mapping_0"] = {
        "homeScreen": "zzmenuPage",
        "directions": [
            {
                "from_name": "menuPage_list_service",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "menuHeading",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['body'][i]['headingParent']['_id']",
                        "target": "$[i]['parent_id']"
                    },
                    {
                        "source": "$['body'][i]['_id']",
                        "target": "$[i]['id']"
                    },
                    {
                        "source": "$['body'][i]['heading']",
                        "target": "$[i]['heading']"
                    },
                    {
                        "source": "$['body'][i]['headingDescription']",
                        "target": "$[i]['description']"
                    },
                    {
                        "source": "$['body'][i]['order']",
                        "target": "$[i]['order']"
                    },
                    {
                        "source": "$['body'][i]['price']",
                        "target": "$[i]['price']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["zzmenuPage_menuPage_list_service_onsuccess_mapping_2"] = {
        "homeScreen": "zzmenuPage",
        "directions": [
            {
                "from_name": "menuHierarchyList",
                "from_type": "VARIABLE_STORAGE",
                "to_name": "zzmenuPage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$[i]",
                        "target_transformation": function(value, element) {
                            element.prop('item_id', value.id);
                            //console.log(JSON.stringify(value));
                            //console.log(element);
                        },
                        "target": "$['headingItem']"
                    },
                    {
                        "source": "$[i]['visible']",
                        "target": "$['headingItem:visible']"
                    },
                    {
                        "source": "$[i]['heading']",
                        "target": "$['headingItem:text']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["zzmenuPage_menuPage_list_service_onbeforesend_mapping_0"] = {
        "homeScreen": "zzmenuPage",
        "directions": [
            {
                "to_name": "menuPage_list_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}"
                    },
                    "parameters": {
                        "include": "vendor,vendor.state,vendor.country,headingParent,headingParent.vendor,headingParent.vendor.state,headingParent.vendor.country,headingParent.headingParent,headingParent.headingParent.vendor,headingParent.headingParent.vendor.state,headingParent.headingParent.vendor.country,headingParent.headingParent.headingParent,headingParent.headingParent.headingParent.vendor,headingParent.headingParent.headingParent.vendor.state,headingParent.headingParent.headingParent.vendor.country,headingParent.headingParent.headingParent.headingParent,headingParent.headingParent.headingParent.headingParent.vendor,headingParent.headingParent.headingParent.headingParent.headingParent",
                        "sort": "order",
                        "where": " {\"vendor\": {\"$inQuery\" : { \"_id\": \"{vendor_id}\"}}}",
                        "limit": "1500"
                    },
                    "body": null
                },
                "mappings": []
            }
        ]
    };
    Apperyio.mappings["zzmenuPage_menuPage_genericMapService_onsuccess_mapping_0"] = {
        "homeScreen": "zzmenuPage",
        "directions": [
            {
                "from_name": "menuHierarchyList",
                "from_type": "VARIABLE_STORAGE",
                "to_name": "zzmenuPage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$[i]",
                        "target_transformation": function(value, element) {
                            return mapMenuItem(value, element);
                        },
                        "target": "$['headingItem']"
                    },
                    {
                        "source": "$[i]['description']",
                        "target_transformation": function(value, element) {
                            return value || '';
                        },
                        "target": "$['headingItem']['menuHeadingDescription:text']"
                    },
                    {
                        "source": "$[i]['visible']",
                        "target": "$['headingItem:visible']"
                    },
                    {
                        "source": "$[i]['isItem']",
                        "target": "$['headingItem']['priceRatingGrid:visible']"
                    },
                    {
                        "source": "$[i]['price']",
                        "target_transformation": function(value, element) {
                            if (value) {
                                return value.toFixed(2);
                            } else {
                                return "";
                            }
                        },
                        "target": "$['headingItem']['priceAmountLabel:text']"
                    },
                    {
                        "source": "$[i]['isHidden']",
                        "target_transformation": function(value, element) {
                            return !value;
                        },
                        "target": "$['headingItem']['selectItemButton:visible']"
                    },
                    {
                        "source": "$[i]['isHidden']",
                        "target": "$['headingItem']['unavailableLabel:visible']"
                    },
                    {
                        "source": "$[i]['isHidden']",
                        "target_transformation": function(value, element) {
                            return value;
                        },
                        "target": "$['headingItem']['addWishListButton:visible']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["zzmenuPage_menuPage_mapService_onsuccess_mapping_0"] = {
        "homeScreen": "zzmenuPage",
        "directions": [
            {
                "from_name": "currentItem",
                "from_type": "SESSION_STORAGE",
                "to_name": "zzmenuPage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['heading']",
                        "target": "$['headingAddField:text']"
                    },
                    {
                        "source": "$['description']",
                        "target": "$['headerDescriptionField:text']"
                    }
                ]
            },
            {
                "from_name": "menuHierarchyList",
                "from_type": "VARIABLE_STORAGE",
                "to_name": "zzmenuPage",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$[i]",
                        "target": "$['headingParentSelect-0']"
                    },
                    {
                        "source": "$[i]['id']",
                        "target": "$['headingParentSelect-0:value']"
                    },
                    {
                        "source": "$[i]['heading']",
                        "target": "$['headingParentSelect-0:label']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["zzmenuPage_menuPage_mapService_onbeforesend_mapping_0"] = {
        "homeScreen": "zzmenuPage",
        "directions": [
            {
                "to_name": "menuPage_mapService",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": null
                },
                "mappings": []
            }
        ]
    };
    Apperyio.mappings["zzmenuPage_menuPage_id_item_query_service_onsuccess_mapping_0"] = {
        "homeScreen": "zzmenuPage",
        "directions": [
            {
                "from_name": "menuPage_id_item_query_service",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "menuItemsList",
                "to_type": "SESSION_STORAGE",
                "mappings": [
                    {
                        "source": "$['body'][i]['_id']",
                        "target": "$[i]['id']"
                    },
                    {
                        "source": "$['body'][i]['name']",
                        "target": "$[i]['heading']"
                    },
                    {
                        "source": "$['body'][i]['heading']['_id']",
                        "target": "$[i]['parent_id']"
                    },
                    {
                        "source": "$['body'][i]['price']",
                        "target": "$[i]['price']"
                    },
                    {
                        "source": "$['body'][i]['order']",
                        "target": "$[i]['order']"
                    },
                    {
                        "source": "$['body'][i]['_id']",
                        "target_transformation": function(value) {
                            return true;
                        },
                        "target": "$[i]['isItem']"
                    },
                    {
                        "source": "$['body'][i]['hidden']",
                        "target": "$[i]['isHidden']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["zzmenuPage_menuPage_id_item_query_service_onbeforesend_mapping_0"] = {
        "homeScreen": "zzmenuPage",
        "directions": [
            {
                "to_name": "menuPage_id_item_query_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}"
                    },
                    "parameters": {
                        "where": " {\"vendor_lk\": {\"$inQuery\" : { \"_id\": \"{vendor_id}\"}}}",
                        "include": "cuisine_lk,ingredientMain_lk,ingredientMain_lk.category_lk,ingredientHidden_lk,ingredientHidden_lk.category_lk,ingredientFeatured_lk,ingredientFeatured_lk.category_lk,rating_lk,rating_lk.item,rating_lk.item.cuisine_lk,rating_lk.item.ingredientMain_lk,rating_lk.item.ingredientMain_lk.category_lk,rating_lk.item.ingredientHidden_lk,rating_lk.item.ingredientFeatured_lk,rating_lk.item.rating_lk,rating_lk.item.vendor_lk,rating_lk.item.heading,rating_lk.user,rating_lk.user.status,vendor_lk,vendor_lk.state,vendor_lk.country,heading,heading.vendor,heading.vendor.state,heading.vendor.country,heading.headingParent",
                        "sort": "order",
                        "limit": "1500"
                    },
                    "body": null
                },
                "mappings": [
                    {
                        "target_transformation": function(value) {
                            return {
                                "vendor_lk": {
                                    "$inQuery": {
                                        "_id": projectMdb1_settings.vendor_id
                                    }
                                }
                            };
                        },
                        "target": "$['parameters']['where']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["zzmenuPage_menuPage_orderItem_create_service_onbeforesend_mapping_0"] = {
        "homeScreen": "zzmenuPage",
        "directions": [
            {
                "from_name": "selectedItem",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuPage_orderItem_create_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": {
                        "quantity": 1,
                        "item": {
                            "collName": "item"
                        },
                        "acl": {
                            "*": {
                                "write": true,
                                "read": true
                            }
                        },
                        "user": {
                            "callName": "_users"
                        }
                    }
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['body']['item']['_id']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["zzmenuPage_menuPage_wishlist_create_service_onbeforesend_mapping_0"] = {
        "homeScreen": "zzmenuPage",
        "directions": [
            {
                "from_name": "selectedItem",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuPage_wishlist_create_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": {
                        "item": {
                            "collName": "item"
                        },
                        "acl": {
                            "*": {
                                "write": true,
                                "read": true
                            }
                        },
                        "user": {
                            "collName": "_users"
                        }
                    }
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['body']['item']['_id']"
                    }
                ]
            },
            {
                "from_name": "zzmenuPage",
                "from_type": "UI",
                "to_name": "menuPage_wishlist_create_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": {
                        "item": {
                            "collName": "item"
                        },
                        "acl": {
                            "*": {
                                "write": true,
                                "read": true
                            }
                        },
                        "user": {
                            "collName": "_users"
                        }
                    }
                },
                "mappings": [
                    {
                        "source": "$['wishListNote:text']",
                        "target": "$['body']['notes']"
                    }
                ]
            },
            {
                "from_name": "userId",
                "from_type": "LOCAL_STORAGE",
                "to_name": "menuPage_wishlist_create_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": {
                        "item": {
                            "collName": "item"
                        },
                        "acl": {
                            "*": {
                                "write": true,
                                "read": true
                            }
                        },
                        "user": {
                            "collName": "_users"
                        }
                    }
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['body']['user']['_id']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["zzmenuPage_menuPage_wishlist_query_service_onbeforesend_mapping_0"] = {
        "homeScreen": "zzmenuPage",
        "directions": [
            {
                "from_name": "selectedItem",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuPage_wishlist_query_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "X-Appery-Session-Token": "{session_token}"
                    },
                    "parameters": {
                        "include": "item,item.cuisine_lk,item.ingredientMain_lk,item.ingredientMain_lk.category_lk,item.ingredientHidden_lk,item.ingredientHidden_lk.category_lk,item.ingredientFeatured_lk,item.ingredientFeatured_lk.category_lk,item.rating_lk,item.rating_lk.item,item.rating_lk.item.cuisine_lk,item.rating_lk.item.ingredientMain_lk,item.rating_lk.item.ingredientHidden_lk,item.rating_lk.item.ingredientFeatured_lk,item.rating_lk.item.rating_lk,item.rating_lk.item.vendor_lk,item.rating_lk.item.heading,item.rating_lk.user,item.rating_lk.user.status,item.rating_lk.user.vendor_lk,item.vendor_lk,item.vendor_lk.state,item.vendor_lk.country,item.heading,item.heading.vendor,item.heading.headingParent,item.heading.owner_lk",
                        "limit": "1500"
                    },
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target_transformation": function(value) {
                            return {
                                "item": {
                                    "$inQuery": {
                                        "_id": value
                                    }
                                }
                            };
                        },
                        "target": "$['parameters']['where']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["zzmenuPage_menuPage_getMenuHierarchy_service_onsuccess_mapping_0"] = {
        "homeScreen": "zzmenuPage",
        "directions": [
            {
                "from_name": "menuPage_getMenuHierarchy_service",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "menuHierarchyList",
                "to_type": "VARIABLE_STORAGE",
                "mappings": [
                    {
                        "source": "$['body'][i]['_id']",
                        "target": "$[i]['id']"
                    },
                    {
                        "source": "$['body'][i]['price']",
                        "target": "$[i]['price']"
                    },
                    {
                        "source": "$['body'][i]['level']",
                        "target": "$[i]['level']"
                    },
                    {
                        "source": "$['body'][i]['opened']",
                        "target": "$[i]['opened']"
                    },
                    {
                        "source": "$['body'][i]['description']",
                        "target": "$[i]['description']"
                    },
                    {
                        "source": "$['body'][i]['heading']",
                        "target": "$[i]['heading']"
                    },
                    {
                        "source": "$['body'][i]['visible']",
                        "target": "$[i]['visible']"
                    },
                    {
                        "source": "$['body'][i]['parent']['_id']",
                        "target": "$[i]['parent_id']"
                    },
                    {
                        "source": "$['body'][i]['hidden']",
                        "target": "$[i]['isHidden']"
                    },
                    {
                        "source": "$['body'][i]['isItem']",
                        "target": "$[i]['isItem']"
                    },
                    {
                        "source": "$['body'][i]['order']",
                        "target": "$[i]['order']"
                    },
                    {
                        "source": "$['body'][i]['hasChildren']",
                        "target": "$[i]['hasChildren']"
                    },
                    {
                        "source": "$['body'][i]['wishlist']",
                        "target": "$[i]['wishlist']"
                    },
                    {
                        "source": "$['body'][i]['favorite']",
                        "target": "$[i]['favorite']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["zzmenuPage_menuPage_getMenuHierarchy_service_onbeforesend_mapping_0"] = {
        "homeScreen": "zzmenuPage",
        "directions": [
            {
                "from_name": "vendorId",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuPage_getMenuHierarchy_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "Content-Type": "application/json"
                    },
                    "parameters": {
                        "vendorId": "{vendor_id}",
                        "openAll": "true",
                        "onlyHeading": "false",
                        "profileUseToggle": "off",
                        "hideEmpty": "on"
                    },
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['parameters']['vendorId']"
                    }
                ]
            },
            {
                "from_name": "sessionToken",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuPage_getMenuHierarchy_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "Content-Type": "application/json"
                    },
                    "parameters": {
                        "vendorId": "{vendor_id}",
                        "openAll": "true",
                        "onlyHeading": "false",
                        "profileUseToggle": "off",
                        "hideEmpty": "on"
                    },
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['headers']['X-Appery-Session-Token']"
                    }
                ]
            },
            {
                "from_name": "zzmenuPage",
                "from_type": "UI",
                "to_name": "menuPage_getMenuHierarchy_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "Content-Type": "application/json"
                    },
                    "parameters": {
                        "vendorId": "{vendor_id}",
                        "openAll": "true",
                        "onlyHeading": "false",
                        "profileUseToggle": "off",
                        "hideEmpty": "on"
                    },
                    "body": null
                },
                "mappings": [
                    {
                        "source": "$['profileUseToggle:toggled']",
                        "target": "$['parameters']['profileUseToggle']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["zzmenuPage_menuPage_createSelected_service_onsuccess_mapping_0"] = {
        "homeScreen": "zzmenuPage",
        "directions": []
    };
    Apperyio.mappings["zzmenuPage_menuPage_createSelected_service_onbeforesend_mapping_0"] = {
        "homeScreen": "zzmenuPage",
        "directions": [
            {
                "from_name": "currentItem",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuPage_createSelected_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": {
                        "itemID": {
                            "collName": "item"
                        },
                        "current": true,
                        "acl": {
                            "*": {
                                "write": true,
                                "read": true
                            }
                        },
                        "userID": {
                            "collName": "_users"
                        },
                        "vendor_lk": {
                            "collName": "vendor"
                        },
                        "fromPage": "menuPage"
                    }
                },
                "mappings": [
                    {
                        "source": "$['id']",
                        "target": "$['body']['itemID']['_id']"
                    },
                    {
                        "source": "$['heading']",
                        "target": "$['body']['itemName']"
                    }
                ]
            },
            {
                "from_name": "userId",
                "from_type": "LOCAL_STORAGE",
                "to_name": "menuPage_createSelected_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": {
                        "itemID": {
                            "collName": "item"
                        },
                        "current": true,
                        "acl": {
                            "*": {
                                "write": true,
                                "read": true
                            }
                        },
                        "userID": {
                            "collName": "_users"
                        },
                        "vendor_lk": {
                            "collName": "vendor"
                        },
                        "fromPage": "menuPage"
                    }
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['body']['userID']['_id']"
                    }
                ]
            },
            {
                "from_name": "currentVendor",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuPage_createSelected_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": {
                        "itemID": {
                            "collName": "item"
                        },
                        "current": true,
                        "acl": {
                            "*": {
                                "write": true,
                                "read": true
                            }
                        },
                        "userID": {
                            "collName": "_users"
                        },
                        "vendor_lk": {
                            "collName": "vendor"
                        },
                        "fromPage": "menuPage"
                    }
                },
                "mappings": [
                    {
                        "source": "$['id']",
                        "target": "$['body']['vendor_lk']['_id']"
                    }
                ]
            },
            {
                "from_name": "sessionToken",
                "from_type": "SESSION_STORAGE",
                "to_name": "menuPage_createSelected_service",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "headers": {
                        "X-Appery-Database-Id": "{database_id}",
                        "Content-Type": "application/json"
                    },
                    "parameters": {},
                    "body": {
                        "itemID": {
                            "collName": "item"
                        },
                        "current": true,
                        "acl": {
                            "*": {
                                "write": true,
                                "read": true
                            }
                        },
                        "userID": {
                            "collName": "_users"
                        },
                        "vendor_lk": {
                            "collName": "vendor"
                        },
                        "fromPage": "menuPage"
                    }
                },
                "mappings": [
                    {
                        "source": "$",
                        "target": "$['headers']['X-Appery-Session-Token']"
                    }
                ]
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.menuPage_list_service = Apperyio.datasources.menuPage_list_service = new Apperyio.DataSource(projectMdb1_menuHeading_list_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["zzmenuPage_menuPage_list_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["zzmenuPage_menuPage_list_service_onsuccess_mapping_0"]);
            makeHierarchy();
            try {
                menuPage_genericMapService.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.menuPage_genericMapService = Apperyio.datasources.menuPage_genericMapService = new Apperyio.DataSource(GenericService, {
        "onBeforeSend": function(jqXHR) {},
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["zzmenuPage_menuPage_genericMapService_onsuccess_mapping_0"]);
            /*
            var scrollTo = storageGet('scrollTo');
            if(scrollTo)
            {
            	//window.scrollTo(0, scrollTo);
                $.mobile.silentScroll(scrollTo);
                //$.mobile.silentScroll(scrollTo);
            }
            storageSet('scrollTo', 0);
            */
            ;
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            showPopupWithTimout('wishlistConfirmPopup', 1000);
        }
    });
    window.menuPage_mapService = Apperyio.datasources.menuPage_mapService = new Apperyio.DataSource(mapMenuHedingItemGenericService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["zzmenuPage_menuPage_mapService_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["zzmenuPage_menuPage_mapService_onsuccess_mapping_0"]);
            //console.log(currentItem);
            Apperyio("headingParentSelect").val(currentItem.parent_id).refresh();;
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.menuPage_id_item_query_service = Apperyio.datasources.menuPage_id_item_query_service = new Apperyio.DataSource(projectMdb1_item_query_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["zzmenuPage_menuPage_id_item_query_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["zzmenuPage_menuPage_id_item_query_service_onsuccess_mapping_0"]);
            try {
                menuPage_list_service.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.menuPage_orderItem_create_service = Apperyio.datasources.menuPage_orderItem_create_service = new Apperyio.DataSource(projectMdb1_orderItem_create_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["zzmenuPage_menuPage_orderItem_create_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            showPopupWithTimout('addToOrderPopup', addToOrderPopupTime);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.menuPage_wishlist_create_service = Apperyio.datasources.menuPage_wishlist_create_service = new Apperyio.DataSource(projectMdb1_wishlist_create_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["zzmenuPage_menuPage_wishlist_create_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            showPopupWithTimout('wishlistConfirmPopup', wishlistConfirmPopupTime);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.menuPage_wishlist_query_service = Apperyio.datasources.menuPage_wishlist_query_service = new Apperyio.DataSource(projectMdb1_wishlist_query_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["zzmenuPage_menuPage_wishlist_query_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            if (!data.length) {
                Apperyio('wishListPopup').popup('open');
            } else {
                showPopupWithTimout('wishlistContainsItem', wishlistContainsItemTime);
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.menuPage_getMenuHierarchy_service = Apperyio.datasources.menuPage_getMenuHierarchy_service = new Apperyio.DataSource(getMenuHierarchy_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["zzmenuPage_menuPage_getMenuHierarchy_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
            hideSpinner();
            window.menuPage_spinnerNeeded = false;
            console.log('Hide spinner...');;
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["zzmenuPage_menuPage_getMenuHierarchy_service_onsuccess_mapping_0"]);
            try {
                menuPage_genericMapService.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    window.menuPage_createSelected_service = Apperyio.datasources.menuPage_createSelected_service = new Apperyio.DataSource(projectMdb1_selected_create_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["zzmenuPage_menuPage_createSelected_service_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["zzmenuPage_menuPage_createSelected_service_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'zzmenuPage';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var zzmenuPage_onLoad = function() {
        zzmenuPage_elementsExtraJS();
        zzmenuPage_deviceEvents();
        zzmenuPage_windowEvents();
        zzmenuPage_elementsEvents();
    };
    // screen window events
    function zzmenuPage_windowEvents() {
        $('#zzmenuPage').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#zzmenuPage').on({
            pageshow: function(event) {
                Apperyio('menuFooter').addClass('fixed-header');
                Apperyio('headingManageHeader').parents('[data-role=header]').addClass('fixed-header');
                initPage();
                Appery('menuTagLine').html(storageGet('currentVendor').menuTagLine || '');
                if (!storageGet('menuHierarchyList')) {
                    window.menuPage_spinnerNeeded = true;
                    setTimeout(function() {
                        /* We check this variable to ensure that showSpinner() will not fire after hideSpinner() */
                        if (window.menuPage_spinnerNeeded) {
                            showSpinner({
                                text: "Loading menu",
                                textVisible: true,
                                textonly: false
                            });
                        }
                    }, 300);
                    console.log('Show spinner...');
                    menuPage_getMenuHierarchy_service.execute({});
                } else {
                    menuPage_genericMapService.execute({});
                };
            },
        });
    };
    // device events
    function zzmenuPage_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function zzmenuPage_elementsExtraJS() {
        // screen (zzmenuPage) extra code
        /* profileUseToggle */
        $("#zzmenuPage_profileUseToggle").parent().find(".ui-flipswitch-on").attr("tabindex", "2");
        /* menuList */
        listView = $("#zzmenuPage_menuList");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#zzmenuPage_menuList .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        /* headingItem */
        /* headingAddPopup */
        $("#zzmenuPage_headingAddPopup").popup("option", "positionTo", "window");
        /* headingParentSelect */
        $("#zzmenuPage_headingParentSelect").parent().find("a.ui-btn").attr("tabindex", "5");
        /* categoryEditPopup */
        $("#zzmenuPage_categoryEditPopup").popup("option", "positionTo", "window");
        /* categoryParentEditButton */
        $("#zzmenuPage_categoryParentEditButton").parent().find("a.ui-btn").attr("tabindex", "7");
        /* itemIsInOrderPopup */
        $("#zzmenuPage_itemIsInOrderPopup").popup("option", "positionTo", "window");
        /* addToOrderPopup */
        $("#zzmenuPage_addToOrderPopup").popup("option", "positionTo", "window");
        /* wishListPopup */
        $("#zzmenuPage_wishListPopup").popup("option", "positionTo", "window");
        /* wishlistConfirmPopup */
        $("#zzmenuPage_wishlistConfirmPopup").popup("option", "positionTo", "window");
        /* wishlistContainsItem */
        $("#zzmenuPage_wishlistContainsItem").popup("option", "positionTo", "window");
        /* loginGotoPopup */
        $("#zzmenuPage_loginGotoPopup").popup("option", "positionTo", "window");
    };
    // screen elements handler
    function zzmenuPage_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#zzmenuPage_headingManageHeader [name="navigateButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    navigateRB();
                }
            },
        }, '#zzmenuPage_headingManageHeader [name="navigateButton"]');
        $(document).off("change", '#zzmenuPage_menuHeadingContainer [name="profileUseToggle"]').on({
            change: function(event) {
                try {
                    menuPage_getMenuHierarchy_service.execute({});
                } catch (e) {
                    console.error(e);
                    hideSpinner();
                };
            },
        }, '#zzmenuPage_menuHeadingContainer [name="profileUseToggle"]');
        $(document).off("click", '#zzmenuPage_menuHeadingContainer [name="collapseExpandButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    collapseExpandAll();
                    menuPage_genericMapService.execute({});
                }
            },
        }, '#zzmenuPage_menuHeadingContainer [name="collapseExpandButton"]');
        $(document).off("click", '#zzmenuPage_menuHeadingContainer [name="headingItem"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    onClickMenuItem(this, menuPage_genericMapService, true);
                }
            },
        }, '#zzmenuPage_menuHeadingContainer [name="headingItem"]');
        $(document).off("click", '#zzmenuPage_menuHeadingContainer [name="selectItemButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var currentItem = _.findWhere(
                            storageGet('menuHierarchyList'), {
                                id: $(this).parents('li').attr('item_id')
                            }
                        ),
                        currentOrder = storageGet('currentOrder') || Apperyio.getModel('currentOrder'),
                        currentOrderItems = storageGet('currentOrderItems') || Apperyio.getModel('orderItems');
                    if (currentOrder.vendor_id !== projectMdb1_settings.vendor_id) {
                        currentOrderItems = [];
                        currentOrder.vendor_id = projectMdb1_settings.vendor_id;
                    }
                    // 
                    currentOrderItems.push({
                        id: currentOrder.items.length + '',
                        item_id: currentItem.id,
                        item_name: currentItem.heading,
                        price: currentItem.price
                    });
                    storageSet('currentOrder', currentOrder);
                    storageSet('currentOrderItems', currentOrderItems);
                    storageSet('currentItem', currentItem);
                    menuPage_createSelected_service.execute({});
                    showPopupWithTimout('addToOrderPopup');
                    //storageSet('selectedItem', $(this).parents('li')[0].item_id);
                    //menuPage_orderItem_create_service.execute({});
                    return false;
                }
            },
        }, '#zzmenuPage_menuHeadingContainer [name="selectItemButton"]');
        $(document).off("click", '#zzmenuPage_menuHeadingContainer [name="addWishListButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    /*
                    if(isGuest)
                    {
                    	Apperyio('loginGotoPopup').popup('open');
                    }
                    else 
                    {
                        Apperyio('wishListNote').val('');
                        storageSet('selectedItem', $(this).parents('li')[0].item_id);
                        menuPage_wishlist_query_service.execute({});
                    }
                    */
                    Apperyio('wishListNote').val('');
                    storageSet('selectedItem', $(this).parents('li').attr('item_id'));
                    menuPage_wishlist_query_service.execute({});
                    return false;
                    ;
                }
            },
        }, '#zzmenuPage_menuHeadingContainer [name="addWishListButton"]');
        $(document).off("click", '#zzmenuPage_menuFooter [name="selectedButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('selectedPage', {
                        reverse: false
                    });
                }
            },
        }, '#zzmenuPage_menuFooter [name="selectedButton"]');
        $(document).off("click", '#zzmenuPage_menuFooter [name="ownerInfoButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('proprietorPage', {
                        transition: 'flip',
                        reverse: false
                    });
                }
            },
        }, '#zzmenuPage_menuFooter [name="ownerInfoButton"]');
        $(document).off("click", '#zzmenuPage_wishListPopup [name="closePopupButton"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio('wishListPopup').popup('close');
                    try {
                        menuPage_wishlist_create_service.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                }
            },
        }, '#zzmenuPage_wishListPopup [name="closePopupButton"]');
    };
    $(document).off("pagebeforeshow", "#zzmenuPage").on("pagebeforeshow", "#zzmenuPage", function(event, ui) {
        Apperyio.CurrentScreen = "zzmenuPage";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    zzmenuPage_onLoad();
};
$(document).off("pagecreate", "#zzmenuPage").on("pagecreate", "#zzmenuPage", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    zzmenuPage_js();
});